In [5]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# import splitting and imputing functions
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer

# turn off pink boxes for demo
import warnings
warnings.filterwarnings("ignore")

# import our own acquire module
import acquire
import os
import env

In [6]:
#imports the dataset 
from pydataset import data

In [5]:
import seaborn as sns

In [6]:
#loads the iris dataset
iris = sns.load_dataset('iris')

In [8]:
# display the first three rows of the Iris dataset
iris.head(3)

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa

In [9]:
# display the dimensions of the Iris dataset
print(iris.shape)

(150, 5)

In [10]:
# display the column names of the Iris dataset
print(iris.columns)

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [11]:
# summarizes useful information about the Iris dataset, 
# including the number of entries, the number of columns, 
# and the data types of each column. 
print(iris.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB
None

In [12]:
print(iris.describe())

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [13]:
print(iris.corr())

              sepal_length  sepal_width  petal_length  petal_width
sepal_length      1.000000    -0.117570      0.871754     0.817941
sepal_width      -0.117570     1.000000     -0.428440    -0.366126
petal_length      0.871754    -0.428440      1.000000     0.962865
petal_width       0.817941    -0.366126      0.962865     1.000000

In [14]:
sheet_url = 'https://docs.google.com/spreadsheets/d/1Uhtml8KY19LILuZsrDtlsHHDC9wuDGUSe8LTEwvdI5g/edit#gid=341089357'

In [15]:
csv_export_url = sheet_url.replace('/edit#gid=', '/export?format=csv&gid=')

In [23]:
titanic_googlesheet = pd.read_csv(csv_export_url)
titanic_googlesheet.head(3)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S

In [24]:
print(titanic_googlesheet.shape)

(891, 12)

In [25]:
print(titanic_googlesheet.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [27]:
print(titanic_googlesheet.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None

In [28]:
print(titanic_googlesheet.columns)

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [29]:
print(titanic_googlesheet.describe())

       PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.523008
std     257.353842    0.486592    0.836071   14.526497    1.102743
min       1.000000    0.000000    1.000000    0.420000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000
50%     446.000000    0.000000    3.000000   28.000000    0.000000
75%     668.500000    1.000000    3.000000   38.000000    1.000000
max     891.000000    1.000000    3.000000   80.000000    8.000000

            Parch        Fare
count  891.000000  891.000000
mean     0.381594   32.204208
std      0.806057   49.693429
min      0.000000    0.000000
25%      0.000000    7.910400
50%      0.000000   14.454200
75%      0.000000   31.000000
max      6.000000  512.329200

In [22]:
print(titanic_googlesheet['Survived'].unique())

[0 1]

In [30]:
print(titanic_googlesheet['Pclass'].unique())

[3 1 2]

In [31]:
print(titanic_googlesheet['Sex'].unique())

['male' 'female']

In [32]:
print(titanic_googlesheet['Embarked'].unique())

['S' 'C' 'Q' nan]

In [7]:
titanic = pd.read_excel('titanic.xlsx')

In [34]:
titanic.head(100)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.00,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38.00,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.00,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.00,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.00,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.00,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.00,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.00,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.00,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.00,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.00,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.00,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.00,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.00,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)",female,31.00,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
20,21,0,2,"Fynney, Mr. Joseph J",male,35.00,0,0,239865,26.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.00,0,0,248698,13.0000,D56,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.00,0,0,330923,8.0292,NaN,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28.00,0,0,113788,35.5000,A6,S
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.00,3,1,349909,21.0750,NaN,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)",female,38.00,1,5,347077,31.3875,NaN,S
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.00,3,2,19950,263.0000,C23 C25 C27,S
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
29,30,0,3,"Todoroff, Mr. Lalio",male,NaN,0,0,349216,7.8958,NaN,S
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.00,0,0,PC 17601,27.7208,NaN,C
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
32,33,1,3,"Glynn, Miss. Mary Agatha",female,NaN,0,0,335677,7.7500,NaN,Q
33,34,0,2,"Wheadon, Mr. Edward H",male,66.00,0,0,C.A. 24579,10.5000,NaN,S
34,35,0,1,"Meyer, Mr. Edgar Joseph",male,28.00,1,0,PC 17604,82.1708,NaN,C
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42.00,1,0,113789,52.0000,NaN,S
36,37,1,3,"Mamee, Mr. Hanna",male,NaN,0,0,2677,7.2292,NaN,C
37,38,0,3,"Cann, Mr. Ernest Charles",male,21.00,0,0,A./5. 2152,8.0500,NaN,S
38,39,0,3,"Vander Planke, Miss. Augusta Maria",female,18.00,2,0,345764,18.0000,NaN,S
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.00,1,0,2651,11.2417,NaN,C
40,41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.00,1,0,7546,9.4750,NaN,S
41,42,0,2,"Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)",female,27.00,1,0,11668,21.0000,NaN,S
42,43,0,3,"Kraeff, Mr. Theodor",male,NaN,0,0,349253,7.8958,NaN,C
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C
44,45,1,3,"Devaney, Miss. Margaret Delia",female,19.00,0,0,330958,7.8792,NaN,Q
45,46,0,3,"Rogers, Mr. William John",male,NaN,0,0,S.C./A.4. 23567,8.0500,NaN,S
46,47,0,3,"Lennon, Mr. Denis",male,NaN,1,0,370371,15.5000,NaN,Q
47,48,1,3,"O'Driscoll, Miss. Bridget",female,NaN,0,0,14311,7.7500,NaN,Q
48,49,0,3,"Samaan, Mr. Youssef",male,NaN,2,0,2662,21.6792,NaN,C
49,50,0,3,"Arnold-Franchi, Mrs. Josef (Josefine Franchi)",female,18.00,1,0,349237,17.8000,NaN,S
50,51,0,3,"Panula, Master. Juha Niilo",male,7.00,4,1,3101295,39.6875,NaN,S
51,52,0,3,"Nosworthy, Mr. Richard Cater",male,21.00,0,0,A/4. 39886,7.8000,NaN,S
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.00,1,0,PC 17572,76.7292,D33,C
53,54,1,2,"Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)",female,29.00,1,0,2926,26.0000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.00,0,1,113509,61.9792,B30,C
55,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S
56,57,1,2,"Rugg, Miss. Emily",female,21.00,0,0,C.A. 31026,10.5000,NaN,S
57,58,0,3,"Novel, Mr. Mansouer",male,28.50,0,0,2697,7.2292,NaN,C
58,59,1,2,"West, Miss. Constance Mirium",female,5.00,1,2,C.A. 34651,27.7500,NaN,S
59,60,0,3,"Goodwin, Master. William Frederick",male,11.00,5,2,CA 2144,46.9000,NaN,S
60,61,0,3,"Sirayanian, Mr. Orsen",male,22.00,0,0,2669,7.2292,NaN,C
61,62,1,1,"Icard, Miss. Amelie",female,38.00,0,0,113572,80.0000,B28,NaN
62,63,0,1,"Harris, Mr. Henry Birkhardt",male,45.00,1,0,36973,83.4750,C83,S
63,64,0,3,"Skoog, Master. Harald",male,4.00,3,2,347088,27.9000,NaN,S
64,65,0,1,"Stewart, Mr. Albert A",male,NaN,0,0,PC 17605,27.7208,NaN,C
65,66,1,3,"Moubarek, Master. Gerios",male,NaN,1,1,2661,15.2458,NaN,C
66,67,1,2,"Nye, Mrs. (Elizabeth Ramell)",female,29.00,0,0,C.A. 29395,10.5000,F33,S
67,68,0,3,"Crease, Mr. Ernest James",male,19.00,0,0,S.P. 3464,8.1583,NaN,S
68,69,1,3,"Andersson, Miss. Erna Alexandra",female,17.00,4,2,3101281,7.9250,NaN,S
69,70,0,3,"Kink, Mr. Vincenz",male,26.00,2,0,315151,8.6625,NaN,S
70,71,0,2,"Jenkin, Mr. Stephen Curnow",male,32.00,0,0,C.A. 33111,10.5000,NaN,S
71,72,0,3,"Goodwin, Miss. Lillian Amy",female,16.00,5,2,CA 2144,46.9000,NaN,S
72,73,0,2,"Hood, Mr. Ambrose Jr",male,21.00,0,0,S.O.C. 14879,73.5000,NaN,S
73,74,0,3,"Chronopoulos, Mr. Apostolos",male,26.00,1,0,2680,14.4542,NaN,C
74,75,1,3,"Bing, Mr. Lee",male,32.00,0,0,1601,56.4958,NaN,S
75,76,0,3,"Moen, Mr. Sigurd Hansen",male,25.00,0,0,348123,7.6500,F G73,S
76,77,0,3,"Staneff, Mr. Ivan",male,NaN,0,0,349208,7.8958,NaN,S
77,78,0,3,"Moutal, Mr. Rahamin Haim",male,NaN,0,0,374746,8.0500,NaN,S
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
79,80,1,3,"Dowdell, Miss. Elizabeth",female,30.00,0,0,364516,12.4750,NaN,S
80,81,0,3,"Waelens, Mr. Achille",male,22.00,0,0,345767,9.0000,NaN,S
81,82,1,3,"Sheerlinck, Mr. Jan Baptist",male,29.00,0,0,345779,9.5000,NaN,S
82,83,1,3,"McDermott, Miss. Brigdet Delia",female,NaN,0,0,330932,7.7875,NaN,Q
83,84,0,1,"Carrau, Mr. Francisco M",male,28.00,0,0,113059,47.1000,NaN,S
84,85,1,2,"Ilett, Miss. Bertha",female,17.00,0,0,SO/C 14885,10.5000,NaN,S
85,86,1,3,"Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)",female,33.00,3,0,3101278,15.8500,NaN,S
86,87,0,3,"Ford, Mr. William Neal",male,16.00,1,3,W./C. 6608,34.3750,NaN,S
87,88,0,3,"Slocovski, Mr. Selman Francis",male,NaN,0,0,SOTON/OQ 392086,8.0500,NaN,S
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.00,3,2,19950,263.0000,C23 C25 C27,S
89,90,0,3,"Celotti, Mr. Francesco",male,24.00,0,0,343275,8.0500,NaN,S
90,91,0,3,"Christmann, Mr. Emil",male,29.00,0,0,343276,8.0500,NaN,S
91,92,0,3,"Andreasson, Mr. Paul Edvin",male,20.00,0,0,347466,7.8542,NaN,S
92,93,0,1,"Chaffee, Mr. Herbert Fuller",male,46.00,1,0,W.E.P. 5734,61.1750,E31,S
93,94,0,3,"Dean, Mr. Bertram Frank",male,26.00,1,2,C.A. 2315,20.5750,NaN,S
94,95,0,3,"Coxon, Mr. Daniel",male,59.00,0,0,364500,7.2500,NaN,S
95,96,0,3,"Shorney, Mr. Charles Joseph",male,NaN,0,0,374910,8.0500,NaN,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.00,0,0,PC 17754,34.6542,A5,C
97,98,1,1,"Greenfield, Mr. William Bertram",male,23.00,0,1,PC 17759,63.3583,D10 D12,C
98,99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34.00,0,1,231919,23.0000,NaN,S
99,100,0,2,"Kantor, Mr. Sinai",male,34.00,1,0,244367,26.0000,NaN,S

In [35]:
df_excel_sample = titanic.head(100)

In [36]:
df_excel_sample

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.00,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Thayer)",female,38.00,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.00,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.00,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.00,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.00,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.00,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.00,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.00,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.00,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.00,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.00,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.00,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.00,0,0,350406,7.8542,NaN,S
15,16,1,2,"Hewlett, Mrs. (Mary D Kingcome)",female,55.00,0,0,248706,16.0000,NaN,S
16,17,0,3,"Rice, Master. Eugene",male,2.00,4,1,382652,29.1250,NaN,Q
17,18,1,2,"Williams, Mr. Charles Eugene",male,NaN,0,0,244373,13.0000,NaN,S
18,19,0,3,"Vander Planke, Mrs. Julius (Emelia Maria Vandemoortele)",female,31.00,1,0,345763,18.0000,NaN,S
19,20,1,3,"Masselmani, Mrs. Fatima",female,NaN,0,0,2649,7.2250,NaN,C
20,21,0,2,"Fynney, Mr. Joseph J",male,35.00,0,0,239865,26.0000,NaN,S
21,22,1,2,"Beesley, Mr. Lawrence",male,34.00,0,0,248698,13.0000,D56,S
22,23,1,3,"McGowan, Miss. Anna ""Annie""",female,15.00,0,0,330923,8.0292,NaN,Q
23,24,1,1,"Sloper, Mr. William Thompson",male,28.00,0,0,113788,35.5000,A6,S
24,25,0,3,"Palsson, Miss. Torborg Danira",female,8.00,3,1,349909,21.0750,NaN,S
25,26,1,3,"Asplund, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)",female,38.00,1,5,347077,31.3875,NaN,S
26,27,0,3,"Emir, Mr. Farred Chehab",male,NaN,0,0,2631,7.2250,NaN,C
27,28,0,1,"Fortune, Mr. Charles Alexander",male,19.00,3,2,19950,263.0000,C23 C25 C27,S
28,29,1,3,"O'Dwyer, Miss. Ellen ""Nellie""",female,NaN,0,0,330959,7.8792,NaN,Q
29,30,0,3,"Todoroff, Mr. Lalio",male,NaN,0,0,349216,7.8958,NaN,S
30,31,0,1,"Uruchurtu, Don. Manuel E",male,40.00,0,0,PC 17601,27.7208,NaN,C
31,32,1,1,"Spencer, Mrs. William Augustus (Marie Eugenie)",female,NaN,1,0,PC 17569,146.5208,B78,C
32,33,1,3,"Glynn, Miss. Mary Agatha",female,NaN,0,0,335677,7.7500,NaN,Q
33,34,0,2,"Wheadon, Mr. Edward H",male,66.00,0,0,C.A. 24579,10.5000,NaN,S
34,35,0,1,"Meyer, Mr. Edgar Joseph",male,28.00,1,0,PC 17604,82.1708,NaN,C
35,36,0,1,"Holverson, Mr. Alexander Oskar",male,42.00,1,0,113789,52.0000,NaN,S
36,37,1,3,"Mamee, Mr. Hanna",male,NaN,0,0,2677,7.2292,NaN,C
37,38,0,3,"Cann, Mr. Ernest Charles",male,21.00,0,0,A./5. 2152,8.0500,NaN,S
38,39,0,3,"Vander Planke, Miss. Augusta Maria",female,18.00,2,0,345764,18.0000,NaN,S
39,40,1,3,"Nicola-Yarred, Miss. Jamila",female,14.00,1,0,2651,11.2417,NaN,C
40,41,0,3,"Ahlin, Mrs. Johan (Johanna Persdotter Larsson)",female,40.00,1,0,7546,9.4750,NaN,S
41,42,0,2,"Turpin, Mrs. William John Robert (Dorothy Ann Wonnacott)",female,27.00,1,0,11668,21.0000,NaN,S
42,43,0,3,"Kraeff, Mr. Theodor",male,NaN,0,0,349253,7.8958,NaN,C
43,44,1,2,"Laroche, Miss. Simonne Marie Anne Andree",female,3.00,1,2,SC/Paris 2123,41.5792,NaN,C
44,45,1,3,"Devaney, Miss. Margaret Delia",female,19.00,0,0,330958,7.8792,NaN,Q
45,46,0,3,"Rogers, Mr. William John",male,NaN,0,0,S.C./A.4. 23567,8.0500,NaN,S
46,47,0,3,"Lennon, Mr. Denis",male,NaN,1,0,370371,15.5000,NaN,Q
47,48,1,3,"O'Driscoll, Miss. Bridget",female,NaN,0,0,14311,7.7500,NaN,Q
48,49,0,3,"Samaan, Mr. Youssef",male,NaN,2,0,2662,21.6792,NaN,C
49,50,0,3,"Arnold-Franchi, Mrs. Josef (Josefine Franchi)",female,18.00,1,0,349237,17.8000,NaN,S
50,51,0,3,"Panula, Master. Juha Niilo",male,7.00,4,1,3101295,39.6875,NaN,S
51,52,0,3,"Nosworthy, Mr. Richard Cater",male,21.00,0,0,A/4. 39886,7.8000,NaN,S
52,53,1,1,"Harper, Mrs. Henry Sleeper (Myna Haxtun)",female,49.00,1,0,PC 17572,76.7292,D33,C
53,54,1,2,"Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkinson)",female,29.00,1,0,2926,26.0000,NaN,S
54,55,0,1,"Ostby, Mr. Engelhart Cornelius",male,65.00,0,1,113509,61.9792,B30,C
55,56,1,1,"Woolner, Mr. Hugh",male,NaN,0,0,19947,35.5000,C52,S
56,57,1,2,"Rugg, Miss. Emily",female,21.00,0,0,C.A. 31026,10.5000,NaN,S
57,58,0,3,"Novel, Mr. Mansouer",male,28.50,0,0,2697,7.2292,NaN,C
58,59,1,2,"West, Miss. Constance Mirium",female,5.00,1,2,C.A. 34651,27.7500,NaN,S
59,60,0,3,"Goodwin, Master. William Frederick",male,11.00,5,2,CA 2144,46.9000,NaN,S
60,61,0,3,"Sirayanian, Mr. Orsen",male,22.00,0,0,2669,7.2292,NaN,C
61,62,1,1,"Icard, Miss. Amelie",female,38.00,0,0,113572,80.0000,B28,NaN
62,63,0,1,"Harris, Mr. Henry Birkhardt",male,45.00,1,0,36973,83.4750,C83,S
63,64,0,3,"Skoog, Master. Harald",male,4.00,3,2,347088,27.9000,NaN,S
64,65,0,1,"Stewart, Mr. Albert A",male,NaN,0,0,PC 17605,27.7208,NaN,C
65,66,1,3,"Moubarek, Master. Gerios",male,NaN,1,1,2661,15.2458,NaN,C
66,67,1,2,"Nye, Mrs. (Elizabeth Ramell)",female,29.00,0,0,C.A. 29395,10.5000,F33,S
67,68,0,3,"Crease, Mr. Ernest James",male,19.00,0,0,S.P. 3464,8.1583,NaN,S
68,69,1,3,"Andersson, Miss. Erna Alexandra",female,17.00,4,2,3101281,7.9250,NaN,S
69,70,0,3,"Kink, Mr. Vincenz",male,26.00,2,0,315151,8.6625,NaN,S
70,71,0,2,"Jenkin, Mr. Stephen Curnow",male,32.00,0,0,C.A. 33111,10.5000,NaN,S
71,72,0,3,"Goodwin, Miss. Lillian Amy",female,16.00,5,2,CA 2144,46.9000,NaN,S
72,73,0,2,"Hood, Mr. Ambrose Jr",male,21.00,0,0,S.O.C. 14879,73.5000,NaN,S
73,74,0,3,"Chronopoulos, Mr. Apostolos",male,26.00,1,0,2680,14.4542,NaN,C
74,75,1,3,"Bing, Mr. Lee",male,32.00,0,0,1601,56.4958,NaN,S
75,76,0,3,"Moen, Mr. Sigurd Hansen",male,25.00,0,0,348123,7.6500,F G73,S
76,77,0,3,"Staneff, Mr. Ivan",male,NaN,0,0,349208,7.8958,NaN,S
77,78,0,3,"Moutal, Mr. Rahamin Haim",male,NaN,0,0,374746,8.0500,NaN,S
78,79,1,2,"Caldwell, Master. Alden Gates",male,0.83,0,2,248738,29.0000,NaN,S
79,80,1,3,"Dowdell, Miss. Elizabeth",female,30.00,0,0,364516,12.4750,NaN,S
80,81,0,3,"Waelens, Mr. Achille",male,22.00,0,0,345767,9.0000,NaN,S
81,82,1,3,"Sheerlinck, Mr. Jan Baptist",male,29.00,0,0,345779,9.5000,NaN,S
82,83,1,3,"McDermott, Miss. Brigdet Delia",female,NaN,0,0,330932,7.7875,NaN,Q
83,84,0,1,"Carrau, Mr. Francisco M",male,28.00,0,0,113059,47.1000,NaN,S
84,85,1,2,"Ilett, Miss. Bertha",female,17.00,0,0,SO/C 14885,10.5000,NaN,S
85,86,1,3,"Backstrom, Mrs. Karl Alfred (Maria Mathilda Gustafsson)",female,33.00,3,0,3101278,15.8500,NaN,S
86,87,0,3,"Ford, Mr. William Neal",male,16.00,1,3,W./C. 6608,34.3750,NaN,S
87,88,0,3,"Slocovski, Mr. Selman Francis",male,NaN,0,0,SOTON/OQ 392086,8.0500,NaN,S
88,89,1,1,"Fortune, Miss. Mabel Helen",female,23.00,3,2,19950,263.0000,C23 C25 C27,S
89,90,0,3,"Celotti, Mr. Francesco",male,24.00,0,0,343275,8.0500,NaN,S
90,91,0,3,"Christmann, Mr. Emil",male,29.00,0,0,343276,8.0500,NaN,S
91,92,0,3,"Andreasson, Mr. Paul Edvin",male,20.00,0,0,347466,7.8542,NaN,S
92,93,0,1,"Chaffee, Mr. Herbert Fuller",male,46.00,1,0,W.E.P. 5734,61.1750,E31,S
93,94,0,3,"Dean, Mr. Bertram Frank",male,26.00,1,2,C.A. 2315,20.5750,NaN,S
94,95,0,3,"Coxon, Mr. Daniel",male,59.00,0,0,364500,7.2500,NaN,S
95,96,0,3,"Shorney, Mr. Charles Joseph",male,NaN,0,0,374910,8.0500,NaN,S
96,97,0,1,"Goldschmidt, Mr. George B",male,71.00,0,0,PC 17754,34.6542,A5,C
97,98,1,1,"Greenfield, Mr. William Bertram",male,23.00,0,1,PC 17759,63.3583,D10 D12,C
98,99,1,2,"Doling, Mrs. John T (Ada Julia Bone)",female,34.00,0,1,231919,23.0000,NaN,S
99,100,0,2,"Kantor, Mr. Sinai",male,34.00,1,0,244367,26.0000,NaN,S

In [37]:
print(titanic.shape)

(891, 12)

In [38]:
print(titanic.columns[:5])

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex'], dtype='object')

In [39]:
obj_type_cols = titanic.select_dtypes(include='object').columns

In [40]:
print(obj_type_cols)

Index(['Name', 'Sex', 'Ticket', 'Cabin', 'Embarked'], dtype='object')

In [41]:
titanic.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [46]:
df = acquire.get_data()

Enter a name for the CSV file: specie_sizes
Enter the name of the database you want to access: iris_db
Enter the name of the table you want to access: measurements
Loading data from specie_sizes
     measurement_id  sepal_length  sepal_width  petal_length  petal_width  \
0                 1           5.1          3.5           1.4          0.2
1                 2           4.9          3.0           1.4          0.2
2                 3           4.7          3.2           1.3          0.2
3                 4           4.6          3.1           1.5          0.2
4                 5           5.0          3.6           1.4          0.2
5                 6           5.4          3.9           1.7          0.4
6                 7           4.6          3.4           1.4          0.3
7                 8           5.0          3.4           1.5          0.2
8                 9           4.4          2.9           1.4          0.2
9                10           4.9          3.1           1.5          0.1
10               11           5.4          3.7           1.5          0.2
11               12           4.8          3.4           1.6          0.2
12               13           4.8          3.0           1.4          0.1
13               14           4.3          3.0           1.1          0.1
14               15           5.8          4.0           1.2          0.2
15               16           5.7          4.4           1.5          0.4
16               17           5.4          3.9           1.3          0.4
17               18           5.1          3.5           1.4          0.3
18               19           5.7          3.8           1.7          0.3
19               20           5.1          3.8           1.5          0.3
20               21           5.4          3.4           1.7          0.2
21               22           5.1          3.7           1.5          0.4
22               23           4.6          3.6           1.0          0.2
23               24           5.1          3.3           1.7          0.5
24               25           4.8          3.4           1.9          0.2
25               26           5.0          3.0           1.6          0.2
26               27           5.0          3.4           1.6          0.4
27               28           5.2          3.5           1.5          0.2
28               29           5.2          3.4           1.4          0.2
29               30           4.7          3.2           1.6          0.2
30               31           4.8          3.1           1.6          0.2
31               32           5.4          3.4           1.5          0.4
32               33           5.2          4.1           1.5          0.1
33               34           5.5          4.2           1.4          0.2
34               35           4.9          3.1           1.5          0.2
35               36           5.0          3.2           1.2          0.2
36               37           5.5          3.5           1.3          0.2
37               38           4.9          3.6           1.4          0.1
38               39           4.4          3.0           1.3          0.2
39               40           5.1          3.4           1.5          0.2
40               41           5.0          3.5           1.3          0.3
41               42           4.5          2.3           1.3          0.3
42               43           4.4          3.2           1.3          0.2
43               44           5.0          3.5           1.6          0.6
44               45           5.1          3.8           1.9          0.4
45               46           4.8          3.0           1.4          0.3
46               47           5.1          3.8           1.6          0.2
47               48           4.6          3.2           1.4          0.2
48               49           5.3          3.7           1.5          0.2
49               50           5.0          3.3           1.4          0.2
50               51           7.0          3.2           4.7          1.4
51               52           6.4          3.2           4.5          1.5
52               53           6.9          3.1           4.9          1.5
53               54           5.5          2.3           4.0          1.3
54               55           6.5          2.8           4.6          1.5
55               56           5.7          2.8           4.5          1.3
56               57           6.3          3.3           4.7          1.6
57               58           4.9          2.4           3.3          1.0
58               59           6.6          2.9           4.6          1.3
59               60           5.2          2.7           3.9          1.4
60               61           5.0          2.0           3.5          1.0
61               62           5.9          3.0           4.2          1.5
62               63           6.0          2.2           4.0          1.0
63               64           6.1          2.9           4.7          1.4
64               65           5.6          2.9           3.6          1.3
65               66           6.7          3.1           4.4          1.4
66               67           5.6          3.0           4.5          1.5
67               68           5.8          2.7           4.1          1.0
68               69           6.2          2.2           4.5          1.5
69               70           5.6          2.5           3.9          1.1
70               71           5.9          3.2           4.8          1.8
71               72           6.1          2.8           4.0          1.3
72               73           6.3          2.5           4.9          1.5
73               74           6.1          2.8           4.7          1.2
74               75           6.4          2.9           4.3          1.3
75               76           6.6          3.0           4.4          1.4
76               77           6.8          2.8           4.8          1.4
77               78           6.7          3.0           5.0          1.7
78               79           6.0          2.9           4.5          1.5
79               80           5.7          2.6           3.5          1.0
80               81           5.5          2.4           3.8          1.1
81               82           5.5          2.4           3.7          1.0
82               83           5.8          2.7           3.9          1.2
83               84           6.0          2.7           5.1          1.6
84               85           5.4          3.0           4.5          1.5
85               86           6.0          3.4           4.5          1.6
86               87           6.7          3.1           4.7          1.5
87               88           6.3          2.3           4.4          1.3
88               89           5.6          3.0           4.1          1.3
89               90           5.5          2.5           4.0          1.3
90               91           5.5          2.6           4.4          1.2
91               92           6.1          3.0           4.6          1.4
92               93           5.8          2.6           4.0          1.2
93               94           5.0          2.3           3.3          1.0
94               95           5.6          2.7           4.2          1.3
95               96           5.7          3.0           4.2          1.2
96               97           5.7          2.9           4.2          1.3
97               98           6.2          2.9           4.3          1.3
98               99           5.1          2.5           3.0          1.1
99              100           5.7          2.8           4.1          1.3
100             101           6.3          3.3           6.0          2.5
101             102           5.8          2.7           5.1          1.9
102             103           7.1          3.0           5.9          2.1
103             104           6.3          2.9           5.6          1.8
104             105           6.5          3.0           5.8          2.2
105             106           7.6          3.0           6.6          2.1
106             107           4.9          2.5           4.5          1.7
107             108           7.3          2.9           6.3          1.8
108             109           6.7          2.5           5.8          1.8
109             110           7.2          3.6           6.1          2.5
110             111           6.5          3.2           5.1          2.0
111             112           6.4          2.7           5.3          1.9
112             113           6.8          3.0           5.5          2.1
113             114           5.7          2.5           5.0          2.0
114             115           5.8          2.8           5.1          2.4
115             116           6.4          3.2           5.3          2.3
116             117           6.5          3.0           5.5          1.8
117             118           7.7          3.8           6.7          2.2
118             119           7.7          2.6           6.9          2.3
119             120           6.0          2.2           5.0          1.5
120             121           6.9          3.2           5.7          2.3
121             122           5.6          2.8           4.9          2.0
122             123           7.7          2.8           6.7          2.0
123             124           6.3          2.7           4.9          1.8
124             125           6.7          3.3           5.7          2.1
125             126           7.2          3.2           6.0          1.8
126             127           6.2          2.8           4.8          1.8
127             128           6.1          3.0           4.9          1.8
128             129           6.4          2.8           5.6          2.1
129             130           7.2          3.0           5.8          1.6
130             131           7.4          2.8           6.1          1.9
131             132           7.9          3.8           6.4          2.0
132             133           6.4          2.8           5.6          2.2
133             134           6.3          2.8           5.1          1.5
134             135           6.1          2.6           5.6          1.4
135             136           7.7          3.0           6.1          2.3
136             137           6.3          3.4           5.6          2.4
137             138           6.4          3.1           5.5          1.8
138             139           6.0          3.0           4.8          1.8
139             140           6.9          3.1           5.4          2.1
140             141           6.7          3.1           5.6          2.4
141             142           6.9          3.1           5.1          2.3
142             143           5.8          2.7           5.1          1.9
143             144           6.8          3.2           5.9          2.3
144             145           6.7          3.3           5.7          2.5
145             146           6.7          3.0           5.2          2.3
146             147           6.3          2.5           5.0          1.9
147             148           6.5          3.0           5.2          2.0
148             149           6.2          3.4           5.4          2.3
149             150           5.9          3.0           5.1          1.8

     species_id
0             1
1             1
2             1
3             1
4             1
5             1
6             1
7             1
8             1
9             1
10            1
11            1
12            1
13            1
14            1
15            1
16            1
17            1
18            1
19            1
20            1
21            1
22            1
23            1
24            1
25            1
26            1
27            1
28            1
29            1
30            1
31            1
32            1
33            1
34            1
35            1
36            1
37            1
38            1
39            1
40            1
41            1
42            1
43            1
44            1
45            1
46            1
47            1
48            1
49            1
50            2
51            2
52            2
53            2
54            2
55            2
56            2
57            2
58            2
59            2
60            2
61            2
62            2
63            2
64            2
65            2
66            2
67            2
68            2
69            2
70            2
71            2
72            2
73            2
74            2
75            2
76            2
77            2
78            2
79            2
80            2
81            2
82            2
83            2
84            2
85            2
86            2
87            2
88            2
89            2
90            2
91            2
92            2
93            2
94            2
95            2
96            2
97            2
98            2
99            2
100           3
101           3
102           3
103           3
104           3
105           3
106           3
107           3
108           3
109           3
110           3
111           3
112           3
113           3
114           3
115           3
116           3
117           3
118           3
119           3
120           3
121           3
122           3
123           3
124           3
125           3
126           3
127           3
128           3
129           3
130           3
131           3
132           3
133           3
134           3
135           3
136           3
137           3
138           3
139           3
140           3
141           3
142           3
143           3
144           3
145           3
146           3
147           3
148           3
149           3

In [47]:
df

,measurement_id,sepal_length,sepal_width,petal_length,petal_width,species_id
0,1,5.1,3.5,1.4,0.2,1
1,2,4.9,3.0,1.4,0.2,1
2,3,4.7,3.2,1.3,0.2,1
3,4,4.6,3.1,1.5,0.2,1
4,5,5.0,3.6,1.4,0.2,1
5,6,5.4,3.9,1.7,0.4,1
6,7,4.6,3.4,1.4,0.3,1
7,8,5.0,3.4,1.5,0.2,1
8,9,4.4,2.9,1.4,0.2,1
9,10,4.9,3.1,1.5,0.1,1
10,11,5.4,3.7,1.5,0.2,1
11,12,4.8,3.4,1.6,0.2,1
12,13,4.8,3.0,1.4,0.1,1
13,14,4.3,3.0,1.1,0.1,1
14,15,5.8,4.0,1.2,0.2,1
15,16,5.7,4.4,1.5,0.4,1
16,17,5.4,3.9,1.3,0.4,1
17,18,5.1,3.5,1.4,0.3,1
18,19,5.7,3.8,1.7,0.3,1
19,20,5.1,3.8,1.5,0.3,1
20,21,5.4,3.4,1.7,0.2,1
21,22,5.1,3.7,1.5,0.4,1
22,23,4.6,3.6,1.0,0.2,1
23,24,5.1,3.3,1.7,0.5,1
24,25,4.8,3.4,1.9,0.2,1
25,26,5.0,3.0,1.6,0.2,1
26,27,5.0,3.4,1.6,0.4,1
27,28,5.2,3.5,1.5,0.2,1
28,29,5.2,3.4,1.4,0.2,1
29,30,4.7,3.2,1.6,0.2,1
30,31,4.8,3.1,1.6,0.2,1
31,32,5.4,3.4,1.5,0.4,1
32,33,5.2,4.1,1.5,0.1,1
33,34,5.5,4.2,1.4,0.2,1
34,35,4.9,3.1,1.5,0.2,1
35,36,5.0,3.2,1.2,0.2,1
36,37,5.5,3.5,1.3,0.2,1
37,38,4.9,3.6,1.4,0.1,1
38,39,4.4,3.0,1.3,0.2,1
39,40,5.1,3.4,1.5,0.2,1
40,41,5.0,3.5,1.3,0.3,1
41,42,4.5,2.3,1.3,0.3,1
42,43,4.4,3.2,1.3,0.2,1
43,44,5.0,3.5,1.6,0.6,1
44,45,5.1,3.8,1.9,0.4,1
45,46,4.8,3.0,1.4,0.3,1
46,47,5.1,3.8,1.6,0.2,1
47,48,4.6,3.2,1.4,0.2,1
48,49,5.3,3.7,1.5,0.2,1
49,50,5.0,3.3,1.4,0.2,1
50,51,7.0,3.2,4.7,1.4,2
51,52,6.4,3.2,4.5,1.5,2
52,53,6.9,3.1,4.9,1.5,2
53,54,5.5,2.3,4.0,1.3,2
54,55,6.5,2.8,4.6,1.5,2
55,56,5.7,2.8,4.5,1.3,2
56,57,6.3,3.3,4.7,1.6,2
57,58,4.9,2.4,3.3,1.0,2
58,59,6.6,2.9,4.6,1.3,2
59,60,5.2,2.7,3.9,1.4,2
60,61,5.0,2.0,3.5,1.0,2
61,62,5.9,3.0,4.2,1.5,2
62,63,6.0,2.2,4.0,1.0,2
63,64,6.1,2.9,4.7,1.4,2
64,65,5.6,2.9,3.6,1.3,2
65,66,6.7,3.1,4.4,1.4,2
66,67,5.6,3.0,4.5,1.5,2
67,68,5.8,2.7,4.1,1.0,2
68,69,6.2,2.2,4.5,1.5,2
69,70,5.6,2.5,3.9,1.1,2
70,71,5.9,3.2,4.8,1.8,2
71,72,6.1,2.8,4.0,1.3,2
72,73,6.3,2.5,4.9,1.5,2
73,74,6.1,2.8,4.7,1.2,2
74,75,6.4,2.9,4.3,1.3,2
75,76,6.6,3.0,4.4,1.4,2
76,77,6.8,2.8,4.8,1.4,2
77,78,6.7,3.0,5.0,1.7,2
78,79,6.0,2.9,4.5,1.5,2
79,80,5.7,2.6,3.5,1.0,2
80,81,5.5,2.4,3.8,1.1,2
81,82,5.5,2.4,3.7,1.0,2
82,83,5.8,2.7,3.9,1.2,2
83,84,6.0,2.7,5.1,1.6,2
84,85,5.4,3.0,4.5,1.5,2
85,86,6.0,3.4,4.5,1.6,2
86,87,6.7,3.1,4.7,1.5,2
87,88,6.3,2.3,4.4,1.3,2
88,89,5.6,3.0,4.1,1.3,2
89,90,5.5,2.5,4.0,1.3,2
90,91,5.5,2.6,4.4,1.2,2
91,92,6.1,3.0,4.6,1.4,2
92,93,5.8,2.6,4.0,1.2,2
93,94,5.0,2.3,3.3,1.0,2
94,95,5.6,2.7,4.2,1.3,2
95,96,5.7,3.0,4.2,1.2,2
96,97,5.7,2.9,4.2,1.3,2
97,98,6.2,2.9,4.3,1.3,2
98,99,5.1,2.5,3.0,1.1,2
99,100,5.7,2.8,4.1,1.3,2
100,101,6.3,3.3,6.0,2.5,3
101,102,5.8,2.7,5.1,1.9,3
102,103,7.1,3.0,5.9,2.1,3
103,104,6.3,2.9,5.6,1.8,3
104,105,6.5,3.0,5.8,2.2,3
105,106,7.6,3.0,6.6,2.1,3
106,107,4.9,2.5,4.5,1.7,3
107,108,7.3,2.9,6.3,1.8,3
108,109,6.7,2.5,5.8,1.8,3
109,110,7.2,3.6,6.1,2.5,3
110,111,6.5,3.2,5.1,2.0,3
111,112,6.4,2.7,5.3,1.9,3
112,113,6.8,3.0,5.5,2.1,3
113,114,5.7,2.5,5.0,2.0,3
114,115,5.8,2.8,5.1,2.4,3
115,116,6.4,3.2,5.3,2.3,3
116,117,6.5,3.0,5.5,1.8,3
117,118,7.7,3.8,6.7,2.2,3
118,119,7.7,2.6,6.9,2.3,3
119,120,6.0,2.2,5.0,1.5,3
120,121,6.9,3.2,5.7,2.3,3
121,122,5.6,2.8,4.9,2.0,3
122,123,7.7,2.8,6.7,2.0,3
123,124,6.3,2.7,4.9,1.8,3
124,125,6.7,3.3,5.7,2.1,3
125,126,7.2,3.2,6.0,1.8,3
126,127,6.2,2.8,4.8,1.8,3
127,128,6.1,3.0,4.9,1.8,3
128,129,6.4,2.8,5.6,2.1,3
129,130,7.2,3.0,5.8,1.6,3
130,131,7.4,2.8,6.1,1.9,3
131,132,7.9,3.8,6.4,2.0,3
132,133,6.4,2.8,5.6,2.2,3
133,134,6.3,2.8,5.1,1.5,3
134,135,6.1,2.6,5.6,1.4,3
135,136,7.7,3.0,6.1,2.3,3
136,137,6.3,3.4,5.6,2.4,3
137,138,6.4,3.1,5.5,1.8,3
138,139,6.0,3.0,4.8,1.8,3
139,140,6.9,3.1,5.4,2.1,3
140,141,6.7,3.1,5.6,2.4,3
141,142,6.9,3.1,5.1,2.3,3
142,143,5.8,2.7,5.1,1.9,3
143,144,6.8,3.2,5.9,2.3,3
144,145,6.7,3.3,5.7,2.5,3
145,146,6.7,3.0,5.2,2.3,3
146,147,6.3,2.5,5.0,1.9,3
147,148,6.5,3.0,5.2,2.0,3
148,149,6.2,3.4,5.4,2.3,3
149,150,5.9,3.0,5.1,1.8,3

In [48]:
df = df.drop('species_id', axis=1)

In [49]:
df

     measurement_id  sepal_length  sepal_width  petal_length  petal_width
0                 1           5.1          3.5           1.4          0.2
1                 2           4.9          3.0           1.4          0.2
2                 3           4.7          3.2           1.3          0.2
3                 4           4.6          3.1           1.5          0.2
4                 5           5.0          3.6           1.4          0.2
5                 6           5.4          3.9           1.7          0.4
6                 7           4.6          3.4           1.4          0.3
7                 8           5.0          3.4           1.5          0.2
8                 9           4.4          2.9           1.4          0.2
9                10           4.9          3.1           1.5          0.1
10               11           5.4          3.7           1.5          0.2
11               12           4.8          3.4           1.6          0.2
12               13           4.8          3.0           1.4          0.1
13               14           4.3          3.0           1.1          0.1
14               15           5.8          4.0           1.2          0.2
15               16           5.7          4.4           1.5          0.4
16               17           5.4          3.9           1.3          0.4
17               18           5.1          3.5           1.4          0.3
18               19           5.7          3.8           1.7          0.3
19               20           5.1          3.8           1.5          0.3
20               21           5.4          3.4           1.7          0.2
21               22           5.1          3.7           1.5          0.4
22               23           4.6          3.6           1.0          0.2
23               24           5.1          3.3           1.7          0.5
24               25           4.8          3.4           1.9          0.2
25               26           5.0          3.0           1.6          0.2
26               27           5.0          3.4           1.6          0.4
27               28           5.2          3.5           1.5          0.2
28               29           5.2          3.4           1.4          0.2
29               30           4.7          3.2           1.6          0.2
30               31           4.8          3.1           1.6          0.2
31               32           5.4          3.4           1.5          0.4
32               33           5.2          4.1           1.5          0.1
33               34           5.5          4.2           1.4          0.2
34               35           4.9          3.1           1.5          0.2
35               36           5.0          3.2           1.2          0.2
36               37           5.5          3.5           1.3          0.2
37               38           4.9          3.6           1.4          0.1
38               39           4.4          3.0           1.3          0.2
39               40           5.1          3.4           1.5          0.2
40               41           5.0          3.5           1.3          0.3
41               42           4.5          2.3           1.3          0.3
42               43           4.4          3.2           1.3          0.2
43               44           5.0          3.5           1.6          0.6
44               45           5.1          3.8           1.9          0.4
45               46           4.8          3.0           1.4          0.3
46               47           5.1          3.8           1.6          0.2
47               48           4.6          3.2           1.4          0.2
48               49           5.3          3.7           1.5          0.2
49               50           5.0          3.3           1.4          0.2
50               51           7.0          3.2           4.7          1.4
51               52           6.4          3.2           4.5          1.5
52               53           6.9          3.1           4.9          1.5
53               54           5.5          2.3           4.0          1.3
54               55           6.5          2.8           4.6          1.5
55               56           5.7          2.8           4.5          1.3
56               57           6.3          3.3           4.7          1.6
57               58           4.9          2.4           3.3          1.0
58               59           6.6          2.9           4.6          1.3
59               60           5.2          2.7           3.9          1.4
60               61           5.0          2.0           3.5          1.0
61               62           5.9          3.0           4.2          1.5
62               63           6.0          2.2           4.0          1.0
63               64           6.1          2.9           4.7          1.4
64               65           5.6          2.9           3.6          1.3
65               66           6.7          3.1           4.4          1.4
66               67           5.6          3.0           4.5          1.5
67               68           5.8          2.7           4.1          1.0
68               69           6.2          2.2           4.5          1.5
69               70           5.6          2.5           3.9          1.1
70               71           5.9          3.2           4.8          1.8
71               72           6.1          2.8           4.0          1.3
72               73           6.3          2.5           4.9          1.5
73               74           6.1          2.8           4.7          1.2
74               75           6.4          2.9           4.3          1.3
75               76           6.6          3.0           4.4          1.4
76               77           6.8          2.8           4.8          1.4
77               78           6.7          3.0           5.0          1.7
78               79           6.0          2.9           4.5          1.5
79               80           5.7          2.6           3.5          1.0
80               81           5.5          2.4           3.8          1.1
81               82           5.5          2.4           3.7          1.0
82               83           5.8          2.7           3.9          1.2
83               84           6.0          2.7           5.1          1.6
84               85           5.4          3.0           4.5          1.5
85               86           6.0          3.4           4.5          1.6
86               87           6.7          3.1           4.7          1.5
87               88           6.3          2.3           4.4          1.3
88               89           5.6          3.0           4.1          1.3
89               90           5.5          2.5           4.0          1.3
90               91           5.5          2.6           4.4          1.2
91               92           6.1          3.0           4.6          1.4
92               93           5.8          2.6           4.0          1.2
93               94           5.0          2.3           3.3          1.0
94               95           5.6          2.7           4.2          1.3
95               96           5.7          3.0           4.2          1.2
96               97           5.7          2.9           4.2          1.3
97               98           6.2          2.9           4.3          1.3
98               99           5.1          2.5           3.0          1.1
99              100           5.7          2.8           4.1          1.3
100             101           6.3          3.3           6.0          2.5
101             102           5.8          2.7           5.1          1.9
102             103           7.1          3.0           5.9          2.1
103             104           6.3          2.9           5.6          1.8
104             105           6.5          3.0           5.8          2.2
105             106           7.6          3.0           6.6          2.1
106             107           4.9          2.5           4.5          1.7
107             108           7.3          2.9           6.3          1.8
108             109           6.7          2.5           5.8          1.8
109             110           7.2          3.6           6.1          2.5
110             111           6.5          3.2           5.1          2.0
111             112           6.4          2.7           5.3          1.9
112             113           6.8          3.0           5.5          2.1
113             114           5.7          2.5           5.0          2.0
114             115           5.8          2.8           5.1          2.4
115             116           6.4          3.2           5.3          2.3
116             117           6.5          3.0           5.5          1.8
117             118           7.7          3.8           6.7          2.2
118             119           7.7          2.6           6.9          2.3
119             120           6.0          2.2           5.0          1.5
120             121           6.9          3.2           5.7          2.3
121             122           5.6          2.8           4.9          2.0
122             123           7.7          2.8           6.7          2.0
123             124           6.3          2.7           4.9          1.8
124             125           6.7          3.3           5.7          2.1
125             126           7.2          3.2           6.0          1.8
126             127           6.2          2.8           4.8          1.8
127             128           6.1          3.0           4.9          1.8
128             129           6.4          2.8           5.6          2.1
129             130           7.2          3.0           5.8          1.6
130             131           7.4          2.8           6.1          1.9
131             132           7.9          3.8           6.4          2.0
132             133           6.4          2.8           5.6          2.2
133             134           6.3          2.8           5.1          1.5
134             135           6.1          2.6           5.6          1.4
135             136           7.7          3.0           6.1          2.3
136             137           6.3          3.4           5.6          2.4
137             138           6.4          3.1           5.5          1.8
138             139           6.0          3.0           4.8          1.8
139             140           6.9          3.1           5.4          2.1
140             141           6.7          3.1           5.6          2.4
141             142           6.9          3.1           5.1          2.3
142             143           5.8          2.7           5.1          1.9
143             144           6.8          3.2           5.9          2.3
144             145           6.7          3.3           5.7          2.5
145             146           6.7          3.0           5.2          2.3
146             147           6.3          2.5           5.0          1.9
147             148           6.5          3.0           5.2          2.0
148             149           6.2          3.4           5.4          2.3
149             150           5.9          3.0           5.1          1.8

In [50]:
df = df.drop('measurement_id', axis=1)

In [51]:
df

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
5             5.4          3.9           1.7          0.4
6             4.6          3.4           1.4          0.3
7             5.0          3.4           1.5          0.2
8             4.4          2.9           1.4          0.2
9             4.9          3.1           1.5          0.1
10            5.4          3.7           1.5          0.2
11            4.8          3.4           1.6          0.2
12            4.8          3.0           1.4          0.1
13            4.3          3.0           1.1          0.1
14            5.8          4.0           1.2          0.2
15            5.7          4.4           1.5          0.4
16            5.4          3.9           1.3          0.4
17            5.1          3.5           1.4          0.3
18            5.7          3.8           1.7          0.3
19            5.1          3.8           1.5          0.3
20            5.4          3.4           1.7          0.2
21            5.1          3.7           1.5          0.4
22            4.6          3.6           1.0          0.2
23            5.1          3.3           1.7          0.5
24            4.8          3.4           1.9          0.2
25            5.0          3.0           1.6          0.2
26            5.0          3.4           1.6          0.4
27            5.2          3.5           1.5          0.2
28            5.2          3.4           1.4          0.2
29            4.7          3.2           1.6          0.2
30            4.8          3.1           1.6          0.2
31            5.4          3.4           1.5          0.4
32            5.2          4.1           1.5          0.1
33            5.5          4.2           1.4          0.2
34            4.9          3.1           1.5          0.2
35            5.0          3.2           1.2          0.2
36            5.5          3.5           1.3          0.2
37            4.9          3.6           1.4          0.1
38            4.4          3.0           1.3          0.2
39            5.1          3.4           1.5          0.2
40            5.0          3.5           1.3          0.3
41            4.5          2.3           1.3          0.3
42            4.4          3.2           1.3          0.2
43            5.0          3.5           1.6          0.6
44            5.1          3.8           1.9          0.4
45            4.8          3.0           1.4          0.3
46            5.1          3.8           1.6          0.2
47            4.6          3.2           1.4          0.2
48            5.3          3.7           1.5          0.2
49            5.0          3.3           1.4          0.2
50            7.0          3.2           4.7          1.4
51            6.4          3.2           4.5          1.5
52            6.9          3.1           4.9          1.5
53            5.5          2.3           4.0          1.3
54            6.5          2.8           4.6          1.5
55            5.7          2.8           4.5          1.3
56            6.3          3.3           4.7          1.6
57            4.9          2.4           3.3          1.0
58            6.6          2.9           4.6          1.3
59            5.2          2.7           3.9          1.4
60            5.0          2.0           3.5          1.0
61            5.9          3.0           4.2          1.5
62            6.0          2.2           4.0          1.0
63            6.1          2.9           4.7          1.4
64            5.6          2.9           3.6          1.3
65            6.7          3.1           4.4          1.4
66            5.6          3.0           4.5          1.5
67            5.8          2.7           4.1          1.0
68            6.2          2.2           4.5          1.5
69            5.6          2.5           3.9          1.1
70            5.9          3.2           4.8          1.8
71            6.1          2.8           4.0          1.3
72            6.3          2.5           4.9          1.5
73            6.1          2.8           4.7          1.2
74            6.4          2.9           4.3          1.3
75            6.6          3.0           4.4          1.4
76            6.8          2.8           4.8          1.4
77            6.7          3.0           5.0          1.7
78            6.0          2.9           4.5          1.5
79            5.7          2.6           3.5          1.0
80            5.5          2.4           3.8          1.1
81            5.5          2.4           3.7          1.0
82            5.8          2.7           3.9          1.2
83            6.0          2.7           5.1          1.6
84            5.4          3.0           4.5          1.5
85            6.0          3.4           4.5          1.6
86            6.7          3.1           4.7          1.5
87            6.3          2.3           4.4          1.3
88            5.6          3.0           4.1          1.3
89            5.5          2.5           4.0          1.3
90            5.5          2.6           4.4          1.2
91            6.1          3.0           4.6          1.4
92            5.8          2.6           4.0          1.2
93            5.0          2.3           3.3          1.0
94            5.6          2.7           4.2          1.3
95            5.7          3.0           4.2          1.2
96            5.7          2.9           4.2          1.3
97            6.2          2.9           4.3          1.3
98            5.1          2.5           3.0          1.1
99            5.7          2.8           4.1          1.3
100           6.3          3.3           6.0          2.5
101           5.8          2.7           5.1          1.9
102           7.1          3.0           5.9          2.1
103           6.3          2.9           5.6          1.8
104           6.5          3.0           5.8          2.2
105           7.6          3.0           6.6          2.1
106           4.9          2.5           4.5          1.7
107           7.3          2.9           6.3          1.8
108           6.7          2.5           5.8          1.8
109           7.2          3.6           6.1          2.5
110           6.5          3.2           5.1          2.0
111           6.4          2.7           5.3          1.9
112           6.8          3.0           5.5          2.1
113           5.7          2.5           5.0          2.0
114           5.8          2.8           5.1          2.4
115           6.4          3.2           5.3          2.3
116           6.5          3.0           5.5          1.8
117           7.7          3.8           6.7          2.2
118           7.7          2.6           6.9          2.3
119           6.0          2.2           5.0          1.5
120           6.9          3.2           5.7          2.3
121           5.6          2.8           4.9          2.0
122           7.7          2.8           6.7          2.0
123           6.3          2.7           4.9          1.8
124           6.7          3.3           5.7          2.1
125           7.2          3.2           6.0          1.8
126           6.2          2.8           4.8          1.8
127           6.1          3.0           4.9          1.8
128           6.4          2.8           5.6          2.1
129           7.2          3.0           5.8          1.6
130           7.4          2.8           6.1          1.9
131           7.9          3.8           6.4          2.0
132           6.4          2.8           5.6          2.2
133           6.3          2.8           5.1          1.5
134           6.1          2.6           5.6          1.4
135           7.7          3.0           6.1          2.3
136           6.3          3.4           5.6          2.4
137           6.4          3.1           5.5          1.8
138           6.0          3.0           4.8          1.8
139           6.9          3.1           5.4          2.1
140           6.7          3.1           5.6          2.4
141           6.9          3.1           5.1          2.3
142           5.8          2.7           5.1          1.9
143           6.8          3.2           5.9          2.3
144           6.7          3.3           5.7          2.5
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

In [53]:
# Rename the 'species_name' column to 'species'
iris = iris.rename(columns={'species_name': 'species'})

In [55]:
iris

,sepal_length,sepal_width,petal_length,petal_width,species,species_setosa,species_versicolor,species_virginica
0,5.1,3.5,1.4,0.2,setosa,1,0,0
1,4.9,3.0,1.4,0.2,setosa,1,0,0
2,4.7,3.2,1.3,0.2,setosa,1,0,0
3,4.6,3.1,1.5,0.2,setosa,1,0,0
4,5.0,3.6,1.4,0.2,setosa,1,0,0
5,5.4,3.9,1.7,0.4,setosa,1,0,0
6,4.6,3.4,1.4,0.3,setosa,1,0,0
7,5.0,3.4,1.5,0.2,setosa,1,0,0
8,4.4,2.9,1.4,0.2,setosa,1,0,0
9,4.9,3.1,1.5,0.1,setosa,1,0,0
10,5.4,3.7,1.5,0.2,setosa,1,0,0
11,4.8,3.4,1.6,0.2,setosa,1,0,0
12,4.8,3.0,1.4,0.1,setosa,1,0,0
13,4.3,3.0,1.1,0.1,setosa,1,0,0
14,5.8,4.0,1.2,0.2,setosa,1,0,0
15,5.7,4.4,1.5,0.4,setosa,1,0,0
16,5.4,3.9,1.3,0.4,setosa,1,0,0
17,5.1,3.5,1.4,0.3,setosa,1,0,0
18,5.7,3.8,1.7,0.3,setosa,1,0,0
19,5.1,3.8,1.5,0.3,setosa,1,0,0
20,5.4,3.4,1.7,0.2,setosa,1,0,0
21,5.1,3.7,1.5,0.4,setosa,1,0,0
22,4.6,3.6,1.0,0.2,setosa,1,0,0
23,5.1,3.3,1.7,0.5,setosa,1,0,0
24,4.8,3.4,1.9,0.2,setosa,1,0,0
25,5.0,3.0,1.6,0.2,setosa,1,0,0
26,5.0,3.4,1.6,0.4,setosa,1,0,0
27,5.2,3.5,1.5,0.2,setosa,1,0,0
28,5.2,3.4,1.4,0.2,setosa,1,0,0
29,4.7,3.2,1.6,0.2,setosa,1,0,0
30,4.8,3.1,1.6,0.2,setosa,1,0,0
31,5.4,3.4,1.5,0.4,setosa,1,0,0
32,5.2,4.1,1.5,0.1,setosa,1,0,0
33,5.5,4.2,1.4,0.2,setosa,1,0,0
34,4.9,3.1,1.5,0.2,setosa,1,0,0
35,5.0,3.2,1.2,0.2,setosa,1,0,0
36,5.5,3.5,1.3,0.2,setosa,1,0,0
37,4.9,3.6,1.4,0.1,setosa,1,0,0
38,4.4,3.0,1.3,0.2,setosa,1,0,0
39,5.1,3.4,1.5,0.2,setosa,1,0,0
40,5.0,3.5,1.3,0.3,setosa,1,0,0
41,4.5,2.3,1.3,0.3,setosa,1,0,0
42,4.4,3.2,1.3,0.2,setosa,1,0,0
43,5.0,3.5,1.6,0.6,setosa,1,0,0
44,5.1,3.8,1.9,0.4,setosa,1,0,0
45,4.8,3.0,1.4,0.3,setosa,1,0,0
46,5.1,3.8,1.6,0.2,setosa,1,0,0
47,4.6,3.2,1.4,0.2,setosa,1,0,0
48,5.3,3.7,1.5,0.2,setosa,1,0,0
49,5.0,3.3,1.4,0.2,setosa,1,0,0
50,7.0,3.2,4.7,1.4,versicolor,0,1,0
51,6.4,3.2,4.5,1.5,versicolor,0,1,0
52,6.9,3.1,4.9,1.5,versicolor,0,1,0
53,5.5,2.3,4.0,1.3,versicolor,0,1,0
54,6.5,2.8,4.6,1.5,versicolor,0,1,0
55,5.7,2.8,4.5,1.3,versicolor,0,1,0
56,6.3,3.3,4.7,1.6,versicolor,0,1,0
57,4.9,2.4,3.3,1.0,versicolor,0,1,0
58,6.6,2.9,4.6,1.3,versicolor,0,1,0
59,5.2,2.7,3.9,1.4,versicolor,0,1,0
60,5.0,2.0,3.5,1.0,versicolor,0,1,0
61,5.9,3.0,4.2,1.5,versicolor,0,1,0
62,6.0,2.2,4.0,1.0,versicolor,0,1,0
63,6.1,2.9,4.7,1.4,versicolor,0,1,0
64,5.6,2.9,3.6,1.3,versicolor,0,1,0
65,6.7,3.1,4.4,1.4,versicolor,0,1,0
66,5.6,3.0,4.5,1.5,versicolor,0,1,0
67,5.8,2.7,4.1,1.0,versicolor,0,1,0
68,6.2,2.2,4.5,1.5,versicolor,0,1,0
69,5.6,2.5,3.9,1.1,versicolor,0,1,0
70,5.9,3.2,4.8,1.8,versicolor,0,1,0
71,6.1,2.8,4.0,1.3,versicolor,0,1,0
72,6.3,2.5,4.9,1.5,versicolor,0,1,0
73,6.1,2.8,4.7,1.2,versicolor,0,1,0
74,6.4,2.9,4.3,1.3,versicolor,0,1,0
75,6.6,3.0,4.4,1.4,versicolor,0,1,0
76,6.8,2.8,4.8,1.4,versicolor,0,1,0
77,6.7,3.0,5.0,1.7,versicolor,0,1,0
78,6.0,2.9,4.5,1.5,versicolor,0,1,0
79,5.7,2.6,3.5,1.0,versicolor,0,1,0
80,5.5,2.4,3.8,1.1,versicolor,0,1,0
81,5.5,2.4,3.7,1.0,versicolor,0,1,0
82,5.8,2.7,3.9,1.2,versicolor,0,1,0
83,6.0,2.7,5.1,1.6,versicolor,0,1,0
84,5.4,3.0,4.5,1.5,versicolor,0,1,0
85,6.0,3.4,4.5,1.6,versicolor,0,1,0
86,6.7,3.1,4.7,1.5,versicolor,0,1,0
87,6.3,2.3,4.4,1.3,versicolor,0,1,0
88,5.6,3.0,4.1,1.3,versicolor,0,1,0
89,5.5,2.5,4.0,1.3,versicolor,0,1,0
90,5.5,2.6,4.4,1.2,versicolor,0,1,0
91,6.1,3.0,4.6,1.4,versicolor,0,1,0
92,5.8,2.6,4.0,1.2,versicolor,0,1,0
93,5.0,2.3,3.3,1.0,versicolor,0,1,0
94,5.6,2.7,4.2,1.3,versicolor,0,1,0
95,5.7,3.0,4.2,1.2,versicolor,0,1,0
96,5.7,2.9,4.2,1.3,versicolor,0,1,0
97,6.2,2.9,4.3,1.3,versicolor,0,1,0
98,5.1,2.5,3.0,1.1,versicolor,0,1,0
99,5.7,2.8,4.1,1.3,versicolor,0,1,0
100,6.3,3.3,6.0,2.5,virginica,0,0,1
101,5.8,2.7,5.1,1.9,virginica,0,0,1
102,7.1,3.0,5.9,2.1,virginica,0,0,1
103,6.3,2.9,5.6,1.8,virginica,0,0,1
104,6.5,3.0,5.8,2.2,virginica,0,0,1
105,7.6,3.0,6.6,2.1,virginica,0,0,1
106,4.9,2.5,4.5,1.7,virginica,0,0,1
107,7.3,2.9,6.3,1.8,virginica,0,0,1
108,6.7,2.5,5.8,1.8,virginica,0,0,1
109,7.2,3.6,6.1,2.5,virginica,0,0,1
110,6.5,3.2,5.1,2.0,virginica,0,0,1
111,6.4,2.7,5.3,1.9,virginica,0,0,1
112,6.8,3.0,5.5,2.1,virginica,0,0,1
113,5.7,2.5,5.0,2.0,virginica,0,0,1
114,5.8,2.8,5.1,2.4,virginica,0,0,1
115,6.4,3.2,5.3,2.3,virginica,0,0,1
116,6.5,3.0,5.5,1.8,virginica,0,0,1
117,7.7,3.8,6.7,2.2,virginica,0,0,1
118,7.7,2.6,6.9,2.3,virginica,0,0,1
119,6.0,2.2,5.0,1.5,virginica,0,0,1
120,6.9,3.2,5.7,2.3,virginica,0,0,1
121,5.6,2.8,4.9,2.0,virginica,0,0,1
122,7.7,2.8,6.7,2.0,virginica,0,0,1
123,6.3,2.7,4.9,1.8,virginica,0,0,1
124,6.7,3.3,5.7,2.1,virginica,0,0,1
125,7.2,3.2,6.0,1.8,virginica,0,0,1
126,6.2,2.8,4.8,1.8,virginica,0,0,1
127,6.1,3.0,4.9,1.8,virginica,0,0,1
128,6.4,2.8,5.6,2.1,virginica,0,0,1
129,7.2,3.0,5.8,1.6,virginica,0,0,1
130,7.4,2.8,6.1,1.9,virginica,0,0,1
131,7.9,3.8,6.4,2.0,virginica,0,0,1
132,6.4,2.8,5.6,2.2,virginica,0,0,1
133,6.3,2.8,5.1,1.5,virginica,0,0,1
134,6.1,2.6,5.6,1.4,virginica,0,0,1
135,7.7,3.0,6.1,2.3,virginica,0,0,1
136,6.3,3.4,5.6,2.4,virginica,0,0,1
137,6.4,3.1,5.5,1.8,virginica,0,0,1
138,6.0,3.0,4.8,1.8,virginica,0,0,1
139,6.9,3.1,5.4,2.1,virginica,0,0,1
140,6.7,3.1,5.6,2.4,virginica,0,0,1
141,6.9,3.1,5.1,2.3,virginica,0,0,1
142,5.8,2.7,5.1,1.9,virginica,0,0,1
143,6.8,3.2,5.9,2.3,virginica,0,0,1
144,6.7,3.3,5.7,2.5,virginica,0,0,1
145,6.7,3.0,5.2,2.3,virginica,0,0,1
146,6.3,2.5,5.0,1.9,virginica,0,0,1
147,6.5,3.0,5.2,2.0,virginica,0,0,1
148,6.2,3.4,5.4,2.3,virginica,0,0,1
149,5.9,3.0,5.1,1.8,virginica,0,0,1

In [54]:
# Create dummy variables of the 'species' column
species_dummies = pd.get_dummies(iris['species'], prefix='species')

In [56]:
species_dummies

     species_setosa  species_versicolor  species_virginica
0                 1                   0                  0
1                 1                   0                  0
2                 1                   0                  0
3                 1                   0                  0
4                 1                   0                  0
5                 1                   0                  0
6                 1                   0                  0
7                 1                   0                  0
8                 1                   0                  0
9                 1                   0                  0
10                1                   0                  0
11                1                   0                  0
12                1                   0                  0
13                1                   0                  0
14                1                   0                  0
15                1                   0                  0
16                1                   0                  0
17                1                   0                  0
18                1                   0                  0
19                1                   0                  0
20                1                   0                  0
21                1                   0                  0
22                1                   0                  0
23                1                   0                  0
24                1                   0                  0
25                1                   0                  0
26                1                   0                  0
27                1                   0                  0
28                1                   0                  0
29                1                   0                  0
30                1                   0                  0
31                1                   0                  0
32                1                   0                  0
33                1                   0                  0
34                1                   0                  0
35                1                   0                  0
36                1                   0                  0
37                1                   0                  0
38                1                   0                  0
39                1                   0                  0
40                1                   0                  0
41                1                   0                  0
42                1                   0                  0
43                1                   0                  0
44                1                   0                  0
45                1                   0                  0
46                1                   0                  0
47                1                   0                  0
48                1                   0                  0
49                1                   0                  0
50                0                   1                  0
51                0                   1                  0
52                0                   1                  0
53                0                   1                  0
54                0                   1                  0
55                0                   1                  0
56                0                   1                  0
57                0                   1                  0
58                0                   1                  0
59                0                   1                  0
60                0                   1                  0
61                0                   1                  0
62                0                   1                  0
63                0                   1                  0
64                0                   1                  0
65                0                   1                  0
66                0                   1                  0
67                0                   1                  0
68                0                   1                  0
69                0                   1                  0
70                0                   1                  0
71                0                   1                  0
72                0                   1                  0
73                0                   1                  0
74                0                   1                  0
75                0                   1                  0
76                0                   1                  0
77                0                   1                  0
78                0                   1                  0
79                0                   1                  0
80                0                   1                  0
81                0                   1                  0
82                0                   1                  0
83                0                   1                  0
84                0                   1                  0
85                0                   1                  0
86                0                   1                  0
87                0                   1                  0
88                0                   1                  0
89                0                   1                  0
90                0                   1                  0
91                0                   1                  0
92                0                   1                  0
93                0                   1                  0
94                0                   1                  0
95                0                   1                  0
96                0                   1                  0
97                0                   1                  0
98                0                   1                  0
99                0                   1                  0
100               0                   0                  1
101               0                   0                  1
102               0                   0                  1
103               0                   0                  1
104               0                   0                  1
105               0                   0                  1
106               0                   0                  1
107               0                   0                  1
108               0                   0                  1
109               0                   0                  1
110               0                   0                  1
111               0                   0                  1
112               0                   0                  1
113               0                   0                  1
114               0                   0                  1
115               0                   0                  1
116               0                   0                  1
117               0                   0                  1
118               0                   0                  1
119               0                   0                  1
120               0                   0                  1
121               0                   0                  1
122               0                   0                  1
123               0                   0                  1
124               0                   0                  1
125               0                   0                  1
126               0                   0                  1
127               0                   0                  1
128               0                   0                  1
129               0                   0                  1
130               0                   0                  1
131               0                   0                  1
132               0                   0                  1
133               0                   0                  1
134               0                   0                  1
135               0                   0                  1
136               0                   0                  1
137               0                   0                  1
138               0                   0                  1
139               0                   0                  1
140               0                   0                  1
141               0                   0                  1
142               0                   0                  1
143               0                   0                  1
144               0                   0                  1
145               0                   0                  1
146               0                   0                  1
147               0                   0                  1
148               0                   0                  1
149               0                   0                  1

In [57]:
# Concatenate the dummy variables onto the original DataFrame
iris = pd.concat([iris, species_dummies], axis=1)

In [58]:
iris

,sepal_length,sepal_width,petal_length,petal_width,species,species_setosa,species_versicolor,species_virginica,species_setosa,species_versicolor,species_virginica
0,5.1,3.5,1.4,0.2,setosa,1,0,0,1,0,0
1,4.9,3.0,1.4,0.2,setosa,1,0,0,1,0,0
2,4.7,3.2,1.3,0.2,setosa,1,0,0,1,0,0
3,4.6,3.1,1.5,0.2,setosa,1,0,0,1,0,0
4,5.0,3.6,1.4,0.2,setosa,1,0,0,1,0,0
5,5.4,3.9,1.7,0.4,setosa,1,0,0,1,0,0
6,4.6,3.4,1.4,0.3,setosa,1,0,0,1,0,0
7,5.0,3.4,1.5,0.2,setosa,1,0,0,1,0,0
8,4.4,2.9,1.4,0.2,setosa,1,0,0,1,0,0
9,4.9,3.1,1.5,0.1,setosa,1,0,0,1,0,0
10,5.4,3.7,1.5,0.2,setosa,1,0,0,1,0,0
11,4.8,3.4,1.6,0.2,setosa,1,0,0,1,0,0
12,4.8,3.0,1.4,0.1,setosa,1,0,0,1,0,0
13,4.3,3.0,1.1,0.1,setosa,1,0,0,1,0,0
14,5.8,4.0,1.2,0.2,setosa,1,0,0,1,0,0
15,5.7,4.4,1.5,0.4,setosa,1,0,0,1,0,0
16,5.4,3.9,1.3,0.4,setosa,1,0,0,1,0,0
17,5.1,3.5,1.4,0.3,setosa,1,0,0,1,0,0
18,5.7,3.8,1.7,0.3,setosa,1,0,0,1,0,0
19,5.1,3.8,1.5,0.3,setosa,1,0,0,1,0,0
20,5.4,3.4,1.7,0.2,setosa,1,0,0,1,0,0
21,5.1,3.7,1.5,0.4,setosa,1,0,0,1,0,0
22,4.6,3.6,1.0,0.2,setosa,1,0,0,1,0,0
23,5.1,3.3,1.7,0.5,setosa,1,0,0,1,0,0
24,4.8,3.4,1.9,0.2,setosa,1,0,0,1,0,0
25,5.0,3.0,1.6,0.2,setosa,1,0,0,1,0,0
26,5.0,3.4,1.6,0.4,setosa,1,0,0,1,0,0
27,5.2,3.5,1.5,0.2,setosa,1,0,0,1,0,0
28,5.2,3.4,1.4,0.2,setosa,1,0,0,1,0,0
29,4.7,3.2,1.6,0.2,setosa,1,0,0,1,0,0
30,4.8,3.1,1.6,0.2,setosa,1,0,0,1,0,0
31,5.4,3.4,1.5,0.4,setosa,1,0,0,1,0,0
32,5.2,4.1,1.5,0.1,setosa,1,0,0,1,0,0
33,5.5,4.2,1.4,0.2,setosa,1,0,0,1,0,0
34,4.9,3.1,1.5,0.2,setosa,1,0,0,1,0,0
35,5.0,3.2,1.2,0.2,setosa,1,0,0,1,0,0
36,5.5,3.5,1.3,0.2,setosa,1,0,0,1,0,0
37,4.9,3.6,1.4,0.1,setosa,1,0,0,1,0,0
38,4.4,3.0,1.3,0.2,setosa,1,0,0,1,0,0
39,5.1,3.4,1.5,0.2,setosa,1,0,0,1,0,0
40,5.0,3.5,1.3,0.3,setosa,1,0,0,1,0,0
41,4.5,2.3,1.3,0.3,setosa,1,0,0,1,0,0
42,4.4,3.2,1.3,0.2,setosa,1,0,0,1,0,0
43,5.0,3.5,1.6,0.6,setosa,1,0,0,1,0,0
44,5.1,3.8,1.9,0.4,setosa,1,0,0,1,0,0
45,4.8,3.0,1.4,0.3,setosa,1,0,0,1,0,0
46,5.1,3.8,1.6,0.2,setosa,1,0,0,1,0,0
47,4.6,3.2,1.4,0.2,setosa,1,0,0,1,0,0
48,5.3,3.7,1.5,0.2,setosa,1,0,0,1,0,0
49,5.0,3.3,1.4,0.2,setosa,1,0,0,1,0,0
50,7.0,3.2,4.7,1.4,versicolor,0,1,0,0,1,0
51,6.4,3.2,4.5,1.5,versicolor,0,1,0,0,1,0
52,6.9,3.1,4.9,1.5,versicolor,0,1,0,0,1,0
53,5.5,2.3,4.0,1.3,versicolor,0,1,0,0,1,0
54,6.5,2.8,4.6,1.5,versicolor,0,1,0,0,1,0
55,5.7,2.8,4.5,1.3,versicolor,0,1,0,0,1,0
56,6.3,3.3,4.7,1.6,versicolor,0,1,0,0,1,0
57,4.9,2.4,3.3,1.0,versicolor,0,1,0,0,1,0
58,6.6,2.9,4.6,1.3,versicolor,0,1,0,0,1,0
59,5.2,2.7,3.9,1.4,versicolor,0,1,0,0,1,0
60,5.0,2.0,3.5,1.0,versicolor,0,1,0,0,1,0
61,5.9,3.0,4.2,1.5,versicolor,0,1,0,0,1,0
62,6.0,2.2,4.0,1.0,versicolor,0,1,0,0,1,0
63,6.1,2.9,4.7,1.4,versicolor,0,1,0,0,1,0
64,5.6,2.9,3.6,1.3,versicolor,0,1,0,0,1,0
65,6.7,3.1,4.4,1.4,versicolor,0,1,0,0,1,0
66,5.6,3.0,4.5,1.5,versicolor,0,1,0,0,1,0
67,5.8,2.7,4.1,1.0,versicolor,0,1,0,0,1,0
68,6.2,2.2,4.5,1.5,versicolor,0,1,0,0,1,0
69,5.6,2.5,3.9,1.1,versicolor,0,1,0,0,1,0
70,5.9,3.2,4.8,1.8,versicolor,0,1,0,0,1,0
71,6.1,2.8,4.0,1.3,versicolor,0,1,0,0,1,0
72,6.3,2.5,4.9,1.5,versicolor,0,1,0,0,1,0
73,6.1,2.8,4.7,1.2,versicolor,0,1,0,0,1,0
74,6.4,2.9,4.3,1.3,versicolor,0,1,0,0,1,0
75,6.6,3.0,4.4,1.4,versicolor,0,1,0,0,1,0
76,6.8,2.8,4.8,1.4,versicolor,0,1,0,0,1,0
77,6.7,3.0,5.0,1.7,versicolor,0,1,0,0,1,0
78,6.0,2.9,4.5,1.5,versicolor,0,1,0,0,1,0
79,5.7,2.6,3.5,1.0,versicolor,0,1,0,0,1,0
80,5.5,2.4,3.8,1.1,versicolor,0,1,0,0,1,0
81,5.5,2.4,3.7,1.0,versicolor,0,1,0,0,1,0
82,5.8,2.7,3.9,1.2,versicolor,0,1,0,0,1,0
83,6.0,2.7,5.1,1.6,versicolor,0,1,0,0,1,0
84,5.4,3.0,4.5,1.5,versicolor,0,1,0,0,1,0
85,6.0,3.4,4.5,1.6,versicolor,0,1,0,0,1,0
86,6.7,3.1,4.7,1.5,versicolor,0,1,0,0,1,0
87,6.3,2.3,4.4,1.3,versicolor,0,1,0,0,1,0
88,5.6,3.0,4.1,1.3,versicolor,0,1,0,0,1,0
89,5.5,2.5,4.0,1.3,versicolor,0,1,0,0,1,0
90,5.5,2.6,4.4,1.2,versicolor,0,1,0,0,1,0
91,6.1,3.0,4.6,1.4,versicolor,0,1,0,0,1,0
92,5.8,2.6,4.0,1.2,versicolor,0,1,0,0,1,0
93,5.0,2.3,3.3,1.0,versicolor,0,1,0,0,1,0
94,5.6,2.7,4.2,1.3,versicolor,0,1,0,0,1,0
95,5.7,3.0,4.2,1.2,versicolor,0,1,0,0,1,0
96,5.7,2.9,4.2,1.3,versicolor,0,1,0,0,1,0
97,6.2,2.9,4.3,1.3,versicolor,0,1,0,0,1,0
98,5.1,2.5,3.0,1.1,versicolor,0,1,0,0,1,0
99,5.7,2.8,4.1,1.3,versicolor,0,1,0,0,1,0
100,6.3,3.3,6.0,2.5,virginica,0,0,1,0,0,1
101,5.8,2.7,5.1,1.9,virginica,0,0,1,0,0,1
102,7.1,3.0,5.9,2.1,virginica,0,0,1,0,0,1
103,6.3,2.9,5.6,1.8,virginica,0,0,1,0,0,1
104,6.5,3.0,5.8,2.2,virginica,0,0,1,0,0,1
105,7.6,3.0,6.6,2.1,virginica,0,0,1,0,0,1
106,4.9,2.5,4.5,1.7,virginica,0,0,1,0,0,1
107,7.3,2.9,6.3,1.8,virginica,0,0,1,0,0,1
108,6.7,2.5,5.8,1.8,virginica,0,0,1,0,0,1
109,7.2,3.6,6.1,2.5,virginica,0,0,1,0,0,1
110,6.5,3.2,5.1,2.0,virginica,0,0,1,0,0,1
111,6.4,2.7,5.3,1.9,virginica,0,0,1,0,0,1
112,6.8,3.0,5.5,2.1,virginica,0,0,1,0,0,1
113,5.7,2.5,5.0,2.0,virginica,0,0,1,0,0,1
114,5.8,2.8,5.1,2.4,virginica,0,0,1,0,0,1
115,6.4,3.2,5.3,2.3,virginica,0,0,1,0,0,1
116,6.5,3.0,5.5,1.8,virginica,0,0,1,0,0,1
117,7.7,3.8,6.7,2.2,virginica,0,0,1,0,0,1
118,7.7,2.6,6.9,2.3,virginica,0,0,1,0,0,1
119,6.0,2.2,5.0,1.5,virginica,0,0,1,0,0,1
120,6.9,3.2,5.7,2.3,virginica,0,0,1,0,0,1
121,5.6,2.8,4.9,2.0,virginica,0,0,1,0,0,1
122,7.7,2.8,6.7,2.0,virginica,0,0,1,0,0,1
123,6.3,2.7,4.9,1.8,virginica,0,0,1,0,0,1
124,6.7,3.3,5.7,2.1,virginica,0,0,1,0,0,1
125,7.2,3.2,6.0,1.8,virginica,0,0,1,0,0,1
126,6.2,2.8,4.8,1.8,virginica,0,0,1,0,0,1
127,6.1,3.0,4.9,1.8,virginica,0,0,1,0,0,1
128,6.4,2.8,5.6,2.1,virginica,0,0,1,0,0,1
129,7.2,3.0,5.8,1.6,virginica,0,0,1,0,0,1
130,7.4,2.8,6.1,1.9,virginica,0,0,1,0,0,1
131,7.9,3.8,6.4,2.0,virginica,0,0,1,0,0,1
132,6.4,2.8,5.6,2.2,virginica,0,0,1,0,0,1
133,6.3,2.8,5.1,1.5,virginica,0,0,1,0,0,1
134,6.1,2.6,5.6,1.4,virginica,0,0,1,0,0,1
135,7.7,3.0,6.1,2.3,virginica,0,0,1,0,0,1
136,6.3,3.4,5.6,2.4,virginica,0,0,1,0,0,1
137,6.4,3.1,5.5,1.8,virginica,0,0,1,0,0,1
138,6.0,3.0,4.8,1.8,virginica,0,0,1,0,0,1
139,6.9,3.1,5.4,2.1,virginica,0,0,1,0,0,1
140,6.7,3.1,5.6,2.4,virginica,0,0,1,0,0,1
141,6.9,3.1,5.1,2.3,virginica,0,0,1,0,0,1
142,5.8,2.7,5.1,1.9,virginica,0,0,1,0,0,1
143,6.8,3.2,5.9,2.3,virginica,0,0,1,0,0,1
144,6.7,3.3,5.7,2.5,virginica,0,0,1,0,0,1
145,6.7,3.0,5.2,2.3,virginica,0,0,1,0,0,1
146,6.3,2.5,5.0,1.9,virginica,0,0,1,0,0,1
147,6.5,3.0,5.2,2.0,virginica,0,0,1,0,0,1
148,6.2,3.4,5.4,2.3,virginica,0,0,1,0,0,1
149,5.9,3.0,5.1,1.8,virginica,0,0,1,0,0,1

In [59]:
def prep_iris(iris):
    # Drop the 'species_id' and 'measurement_id' columns
    iris = iris.drop(['species_id', 'measurement_id'], axis=1)
    
    # Rename the 'species_name' column to 'species'
    iris = iris.rename(columns={'species_name': 'species'})
    
    # Create dummy variables of the 'species' column
    species_dummies = pd.get_dummies(iris['species'], prefix='species')
    
    # Concatenate the dummy variables onto the original DataFrame
    iris = pd.concat([iris, species_dummies], axis=1)
    
    return iris

In [61]:
iris

,sepal_length,sepal_width,petal_length,petal_width,species,species_setosa,species_versicolor,species_virginica,species_setosa,species_versicolor,species_virginica
0,5.1,3.5,1.4,0.2,setosa,1,0,0,1,0,0
1,4.9,3.0,1.4,0.2,setosa,1,0,0,1,0,0
2,4.7,3.2,1.3,0.2,setosa,1,0,0,1,0,0
3,4.6,3.1,1.5,0.2,setosa,1,0,0,1,0,0
4,5.0,3.6,1.4,0.2,setosa,1,0,0,1,0,0
5,5.4,3.9,1.7,0.4,setosa,1,0,0,1,0,0
6,4.6,3.4,1.4,0.3,setosa,1,0,0,1,0,0
7,5.0,3.4,1.5,0.2,setosa,1,0,0,1,0,0
8,4.4,2.9,1.4,0.2,setosa,1,0,0,1,0,0
9,4.9,3.1,1.5,0.1,setosa,1,0,0,1,0,0
10,5.4,3.7,1.5,0.2,setosa,1,0,0,1,0,0
11,4.8,3.4,1.6,0.2,setosa,1,0,0,1,0,0
12,4.8,3.0,1.4,0.1,setosa,1,0,0,1,0,0
13,4.3,3.0,1.1,0.1,setosa,1,0,0,1,0,0
14,5.8,4.0,1.2,0.2,setosa,1,0,0,1,0,0
15,5.7,4.4,1.5,0.4,setosa,1,0,0,1,0,0
16,5.4,3.9,1.3,0.4,setosa,1,0,0,1,0,0
17,5.1,3.5,1.4,0.3,setosa,1,0,0,1,0,0
18,5.7,3.8,1.7,0.3,setosa,1,0,0,1,0,0
19,5.1,3.8,1.5,0.3,setosa,1,0,0,1,0,0
20,5.4,3.4,1.7,0.2,setosa,1,0,0,1,0,0
21,5.1,3.7,1.5,0.4,setosa,1,0,0,1,0,0
22,4.6,3.6,1.0,0.2,setosa,1,0,0,1,0,0
23,5.1,3.3,1.7,0.5,setosa,1,0,0,1,0,0
24,4.8,3.4,1.9,0.2,setosa,1,0,0,1,0,0
25,5.0,3.0,1.6,0.2,setosa,1,0,0,1,0,0
26,5.0,3.4,1.6,0.4,setosa,1,0,0,1,0,0
27,5.2,3.5,1.5,0.2,setosa,1,0,0,1,0,0
28,5.2,3.4,1.4,0.2,setosa,1,0,0,1,0,0
29,4.7,3.2,1.6,0.2,setosa,1,0,0,1,0,0
30,4.8,3.1,1.6,0.2,setosa,1,0,0,1,0,0
31,5.4,3.4,1.5,0.4,setosa,1,0,0,1,0,0
32,5.2,4.1,1.5,0.1,setosa,1,0,0,1,0,0
33,5.5,4.2,1.4,0.2,setosa,1,0,0,1,0,0
34,4.9,3.1,1.5,0.2,setosa,1,0,0,1,0,0
35,5.0,3.2,1.2,0.2,setosa,1,0,0,1,0,0
36,5.5,3.5,1.3,0.2,setosa,1,0,0,1,0,0
37,4.9,3.6,1.4,0.1,setosa,1,0,0,1,0,0
38,4.4,3.0,1.3,0.2,setosa,1,0,0,1,0,0
39,5.1,3.4,1.5,0.2,setosa,1,0,0,1,0,0
40,5.0,3.5,1.3,0.3,setosa,1,0,0,1,0,0
41,4.5,2.3,1.3,0.3,setosa,1,0,0,1,0,0
42,4.4,3.2,1.3,0.2,setosa,1,0,0,1,0,0
43,5.0,3.5,1.6,0.6,setosa,1,0,0,1,0,0
44,5.1,3.8,1.9,0.4,setosa,1,0,0,1,0,0
45,4.8,3.0,1.4,0.3,setosa,1,0,0,1,0,0
46,5.1,3.8,1.6,0.2,setosa,1,0,0,1,0,0
47,4.6,3.2,1.4,0.2,setosa,1,0,0,1,0,0
48,5.3,3.7,1.5,0.2,setosa,1,0,0,1,0,0
49,5.0,3.3,1.4,0.2,setosa,1,0,0,1,0,0
50,7.0,3.2,4.7,1.4,versicolor,0,1,0,0,1,0
51,6.4,3.2,4.5,1.5,versicolor,0,1,0,0,1,0
52,6.9,3.1,4.9,1.5,versicolor,0,1,0,0,1,0
53,5.5,2.3,4.0,1.3,versicolor,0,1,0,0,1,0
54,6.5,2.8,4.6,1.5,versicolor,0,1,0,0,1,0
55,5.7,2.8,4.5,1.3,versicolor,0,1,0,0,1,0
56,6.3,3.3,4.7,1.6,versicolor,0,1,0,0,1,0
57,4.9,2.4,3.3,1.0,versicolor,0,1,0,0,1,0
58,6.6,2.9,4.6,1.3,versicolor,0,1,0,0,1,0
59,5.2,2.7,3.9,1.4,versicolor,0,1,0,0,1,0
60,5.0,2.0,3.5,1.0,versicolor,0,1,0,0,1,0
61,5.9,3.0,4.2,1.5,versicolor,0,1,0,0,1,0
62,6.0,2.2,4.0,1.0,versicolor,0,1,0,0,1,0
63,6.1,2.9,4.7,1.4,versicolor,0,1,0,0,1,0
64,5.6,2.9,3.6,1.3,versicolor,0,1,0,0,1,0
65,6.7,3.1,4.4,1.4,versicolor,0,1,0,0,1,0
66,5.6,3.0,4.5,1.5,versicolor,0,1,0,0,1,0
67,5.8,2.7,4.1,1.0,versicolor,0,1,0,0,1,0
68,6.2,2.2,4.5,1.5,versicolor,0,1,0,0,1,0
69,5.6,2.5,3.9,1.1,versicolor,0,1,0,0,1,0
70,5.9,3.2,4.8,1.8,versicolor,0,1,0,0,1,0
71,6.1,2.8,4.0,1.3,versicolor,0,1,0,0,1,0
72,6.3,2.5,4.9,1.5,versicolor,0,1,0,0,1,0
73,6.1,2.8,4.7,1.2,versicolor,0,1,0,0,1,0
74,6.4,2.9,4.3,1.3,versicolor,0,1,0,0,1,0
75,6.6,3.0,4.4,1.4,versicolor,0,1,0,0,1,0
76,6.8,2.8,4.8,1.4,versicolor,0,1,0,0,1,0
77,6.7,3.0,5.0,1.7,versicolor,0,1,0,0,1,0
78,6.0,2.9,4.5,1.5,versicolor,0,1,0,0,1,0
79,5.7,2.6,3.5,1.0,versicolor,0,1,0,0,1,0
80,5.5,2.4,3.8,1.1,versicolor,0,1,0,0,1,0
81,5.5,2.4,3.7,1.0,versicolor,0,1,0,0,1,0
82,5.8,2.7,3.9,1.2,versicolor,0,1,0,0,1,0
83,6.0,2.7,5.1,1.6,versicolor,0,1,0,0,1,0
84,5.4,3.0,4.5,1.5,versicolor,0,1,0,0,1,0
85,6.0,3.4,4.5,1.6,versicolor,0,1,0,0,1,0
86,6.7,3.1,4.7,1.5,versicolor,0,1,0,0,1,0
87,6.3,2.3,4.4,1.3,versicolor,0,1,0,0,1,0
88,5.6,3.0,4.1,1.3,versicolor,0,1,0,0,1,0
89,5.5,2.5,4.0,1.3,versicolor,0,1,0,0,1,0
90,5.5,2.6,4.4,1.2,versicolor,0,1,0,0,1,0
91,6.1,3.0,4.6,1.4,versicolor,0,1,0,0,1,0
92,5.8,2.6,4.0,1.2,versicolor,0,1,0,0,1,0
93,5.0,2.3,3.3,1.0,versicolor,0,1,0,0,1,0
94,5.6,2.7,4.2,1.3,versicolor,0,1,0,0,1,0
95,5.7,3.0,4.2,1.2,versicolor,0,1,0,0,1,0
96,5.7,2.9,4.2,1.3,versicolor,0,1,0,0,1,0
97,6.2,2.9,4.3,1.3,versicolor,0,1,0,0,1,0
98,5.1,2.5,3.0,1.1,versicolor,0,1,0,0,1,0
99,5.7,2.8,4.1,1.3,versicolor,0,1,0,0,1,0
100,6.3,3.3,6.0,2.5,virginica,0,0,1,0,0,1
101,5.8,2.7,5.1,1.9,virginica,0,0,1,0,0,1
102,7.1,3.0,5.9,2.1,virginica,0,0,1,0,0,1
103,6.3,2.9,5.6,1.8,virginica,0,0,1,0,0,1
104,6.5,3.0,5.8,2.2,virginica,0,0,1,0,0,1
105,7.6,3.0,6.6,2.1,virginica,0,0,1,0,0,1
106,4.9,2.5,4.5,1.7,virginica,0,0,1,0,0,1
107,7.3,2.9,6.3,1.8,virginica,0,0,1,0,0,1
108,6.7,2.5,5.8,1.8,virginica,0,0,1,0,0,1
109,7.2,3.6,6.1,2.5,virginica,0,0,1,0,0,1
110,6.5,3.2,5.1,2.0,virginica,0,0,1,0,0,1
111,6.4,2.7,5.3,1.9,virginica,0,0,1,0,0,1
112,6.8,3.0,5.5,2.1,virginica,0,0,1,0,0,1
113,5.7,2.5,5.0,2.0,virginica,0,0,1,0,0,1
114,5.8,2.8,5.1,2.4,virginica,0,0,1,0,0,1
115,6.4,3.2,5.3,2.3,virginica,0,0,1,0,0,1
116,6.5,3.0,5.5,1.8,virginica,0,0,1,0,0,1
117,7.7,3.8,6.7,2.2,virginica,0,0,1,0,0,1
118,7.7,2.6,6.9,2.3,virginica,0,0,1,0,0,1
119,6.0,2.2,5.0,1.5,virginica,0,0,1,0,0,1
120,6.9,3.2,5.7,2.3,virginica,0,0,1,0,0,1
121,5.6,2.8,4.9,2.0,virginica,0,0,1,0,0,1
122,7.7,2.8,6.7,2.0,virginica,0,0,1,0,0,1
123,6.3,2.7,4.9,1.8,virginica,0,0,1,0,0,1
124,6.7,3.3,5.7,2.1,virginica,0,0,1,0,0,1
125,7.2,3.2,6.0,1.8,virginica,0,0,1,0,0,1
126,6.2,2.8,4.8,1.8,virginica,0,0,1,0,0,1
127,6.1,3.0,4.9,1.8,virginica,0,0,1,0,0,1
128,6.4,2.8,5.6,2.1,virginica,0,0,1,0,0,1
129,7.2,3.0,5.8,1.6,virginica,0,0,1,0,0,1
130,7.4,2.8,6.1,1.9,virginica,0,0,1,0,0,1
131,7.9,3.8,6.4,2.0,virginica,0,0,1,0,0,1
132,6.4,2.8,5.6,2.2,virginica,0,0,1,0,0,1
133,6.3,2.8,5.1,1.5,virginica,0,0,1,0,0,1
134,6.1,2.6,5.6,1.4,virginica,0,0,1,0,0,1
135,7.7,3.0,6.1,2.3,virginica,0,0,1,0,0,1
136,6.3,3.4,5.6,2.4,virginica,0,0,1,0,0,1
137,6.4,3.1,5.5,1.8,virginica,0,0,1,0,0,1
138,6.0,3.0,4.8,1.8,virginica,0,0,1,0,0,1
139,6.9,3.1,5.4,2.1,virginica,0,0,1,0,0,1
140,6.7,3.1,5.6,2.4,virginica,0,0,1,0,0,1
141,6.9,3.1,5.1,2.3,virginica,0,0,1,0,0,1
142,5.8,2.7,5.1,1.9,virginica,0,0,1,0,0,1
143,6.8,3.2,5.9,2.3,virginica,0,0,1,0,0,1
144,6.7,3.3,5.7,2.5,virginica,0,0,1,0,0,1
145,6.7,3.0,5.2,2.3,virginica,0,0,1,0,0,1
146,6.3,2.5,5.0,1.9,virginica,0,0,1,0,0,1
147,6.5,3.0,5.2,2.0,virginica,0,0,1,0,0,1
148,6.2,3.4,5.4,2.3,virginica,0,0,1,0,0,1
149,5.9,3.0,5.1,1.8,virginica,0,0,1,0,0,1

In [8]:
# Drop the unnecessary columns
titanic = titanic.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)

In [9]:
titanic

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [12]:
# Create dummy variables of the categorical columns
sex_dummies = pd.get_dummies(titanic['Sex'], prefix='sex')
embarked_dummies = pd.get_dummies(titanic['Embarked'], prefix='embarked')
pclass_dummies = pd.get_dummies(titanic['Pclass'], prefix='pclass')

In [13]:
titanic

     Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0           0       3    male  22.0      1      0   7.2500        S
1           1       1  female  38.0      1      0  71.2833        C
2           1       3  female  26.0      0      0   7.9250        S
3           1       1  female  35.0      1      0  53.1000        S
4           0       3    male  35.0      0      0   8.0500        S
..        ...     ...     ...   ...    ...    ...      ...      ...
886         0       2    male  27.0      0      0  13.0000        S
887         1       1  female  19.0      0      0  30.0000        S
888         0       3  female   NaN      1      2  23.4500        S
889         1       1    male  26.0      0      0  30.0000        C
890         0       3    male  32.0      0      0   7.7500        Q

[891 rows x 8 columns]

In [14]:
# Concatenate the dummy variables onto the original DataFrame
titanic = pd.concat([titanic, sex_dummies, embarked_dummies, pclass_dummies], axis=1)

In [15]:
titanic

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked,sex_female,sex_male,embarked_C,embarked_Q,embarked_S,pclass_1,pclass_2,pclass_3
0,0,3,male,22.0,1,0,7.2500,S,0,1,0,0,1,0,0,1
1,1,1,female,38.0,1,0,71.2833,C,1,0,1,0,0,1,0,0
2,1,3,female,26.0,0,0,7.9250,S,1,0,0,0,1,0,0,1
3,1,1,female,35.0,1,0,53.1000,S,1,0,0,0,1,1,0,0
4,0,3,male,35.0,0,0,8.0500,S,0,1,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,0,1,0,0,1,0,1,0
887,1,1,female,19.0,0,0,30.0000,S,1,0,0,0,1,1,0,0
888,0,3,female,NaN,1,2,23.4500,S,1,0,0,0,1,0,0,1
889,1,1,male,26.0,0,0,30.0000,C,0,1,1,0,0,1,0,0
890,0,3,male,32.0,0,0,7.7500,Q,0,1,0,1,0,0,0,1

In [16]:
# Drop the original categorical columns
titanic = titanic.drop(['Sex', 'Embarked', 'Pclass'], axis=1)

In [17]:
titanic

,Survived,Age,SibSp,Parch,Fare,sex_female,sex_male,embarked_C,embarked_Q,embarked_S,pclass_1,pclass_2,pclass_3
0,0,22.0,1,0,7.2500,0,1,0,0,1,0,0,1
1,1,38.0,1,0,71.2833,1,0,1,0,0,1,0,0
2,1,26.0,0,0,7.9250,1,0,0,0,1,0,0,1
3,1,35.0,1,0,53.1000,1,0,0,0,1,1,0,0
4,0,35.0,0,0,8.0500,0,1,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,27.0,0,0,13.0000,0,1,0,0,1,0,1,0
887,1,19.0,0,0,30.0000,1,0,0,0,1,1,0,0
888,0,NaN,1,2,23.4500,1,0,0,0,1,0,0,1
889,1,26.0,0,0,30.0000,0,1,1,0,0,1,0,0
890,0,32.0,0,0,7.7500,0,1,0,1,0,0,0,1

In [18]:
def prep_titanic(titanic):
    # Drop the unnecessary columns
    titanic = titanic.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis=1)
    
    # Create dummy variables of the categorical columns
    sex_dummies = pd.get_dummies(titanic['Sex'], prefix='sex')
    embarked_dummies = pd.get_dummies(titanic['Embarked'], prefix='embarked')
    pclass_dummies = pd.get_dummies(titanic['Pclass'], prefix='pclass')
    
    # Concatenate the dummy variables onto the original DataFrame
    titanic = pd.concat([titanic, sex_dummies, embarked_dummies, pclass_dummies], axis=1)
    
    # Drop the original categorical columns
    titanic = titanic.drop(['Sex', 'Embarked', 'Pclass'], axis=1)
    
    return titanic

In [19]:
titanic

,Survived,Age,SibSp,Parch,Fare,sex_female,sex_male,embarked_C,embarked_Q,embarked_S,pclass_1,pclass_2,pclass_3
0,0,22.0,1,0,7.2500,0,1,0,0,1,0,0,1
1,1,38.0,1,0,71.2833,1,0,1,0,0,1,0,0
2,1,26.0,0,0,7.9250,1,0,0,0,1,0,0,1
3,1,35.0,1,0,53.1000,1,0,0,0,1,1,0,0
4,0,35.0,0,0,8.0500,0,1,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,27.0,0,0,13.0000,0,1,0,0,1,0,1,0
887,1,19.0,0,0,30.0000,1,0,0,0,1,1,0,0
888,0,NaN,1,2,23.4500,1,0,0,0,1,0,0,1
889,1,26.0,0,0,30.0000,0,1,1,0,0,1,0,0
890,0,32.0,0,0,7.7500,0,1,0,1,0,0,0,1

In [33]:
df = acquire.get_data()

Enter a name for the CSV file: telco_churn.csv
Enter the name of the database you want to access: telco_churn
Enter the name of the table you want to access: customers
Loading data from telco_churn.csv
      customerID  gender  SeniorCitizen Partner Dependents  tenure  \
0     7590-VHVEG  Female              0     Yes         No       1
1     5575-GNVDE    Male              0      No         No      34
2     3668-QPYBK    Male              0      No         No       2
3     7795-CFOCW    Male              0      No         No      45
4     9237-HQITU  Female              0      No         No       2
...          ...     ...            ...     ...        ...     ...
7038  6840-RESVB    Male              0     Yes        Yes      24
7039  2234-XADUH  Female              0     Yes        Yes      72
7040  4801-JZAZL  Female              0     Yes        Yes      11
7041  8361-LTMKD    Male              1     Yes         No       4
7042  3186-AJIEK    Male              0      No         No      66

     PhoneService     MultipleLines InternetService OnlineSecurity  ...  \
0              No  No phone service             DSL             No  ...
1             Yes                No             DSL            Yes  ...
2             Yes                No             DSL            Yes  ...
3              No  No phone service             DSL            Yes  ...
4             Yes                No     Fiber optic             No  ...
...           ...               ...             ...            ...  ...
7038          Yes               Yes             DSL            Yes  ...
7039          Yes               Yes     Fiber optic             No  ...
7040           No  No phone service             DSL            Yes  ...
7041          Yes               Yes     Fiber optic             No  ...
7042          Yes                No     Fiber optic            Yes  ...

     DeviceProtection TechSupport StreamingTV StreamingMovies        Contract  \
0                  No          No          No              No  Month-to-month
1                 Yes          No          No              No        One year
2                  No          No          No              No  Month-to-month
3                 Yes         Yes          No              No        One year
4                  No          No          No              No  Month-to-month
...               ...         ...         ...             ...             ...
7038              Yes         Yes         Yes             Yes        One year
7039              Yes          No         Yes             Yes        One year
7040               No          No          No              No  Month-to-month
7041               No          No          No              No  Month-to-month
7042              Yes         Yes         Yes             Yes        Two year

     PaperlessBilling              PaymentMethod MonthlyCharges  TotalCharges  \
0                 Yes           Electronic check          29.85         29.85
1                  No               Mailed check          56.95       1889.50
2                 Yes               Mailed check          53.85        108.15
3                  No  Bank transfer (automatic)          42.30       1840.75
4                 Yes           Electronic check          70.70        151.65
...               ...                        ...            ...           ...
7038              Yes               Mailed check          84.80       1990.50
7039              Yes    Credit card (automatic)         103.20       7362.90
7040              Yes           Electronic check          29.60        346.45
7041              Yes               Mailed check          74.40        306.60
7042              Yes  Bank transfer (automatic)         105.65       6844.50

      Churn
0        No
1        No
2       Yes
3        No
4       Yes
...     ...
7038     No
7039     No
7040     No
7041    Yes
7042     No

[7043 rows x 21 columns]

In [44]:
telco_churn = df

In [45]:
telco_churn

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No

In [47]:
telco_churn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7043 non-null   object
dtypes: float64(2), int64(2), object(17)
memory usage: 1.1+ MB

In [50]:
# Drop the unnecessary columns
telco_churn = telco_churn.drop(['customerID', 'gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 
                    'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
                    'StreamingMovies', 'PaperlessBilling', 'PaymentMethod'], axis=1)

In [56]:
telco_churn

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,Churn,InternetService_DSL,InternetService_Fiber optic,InternetService_No,Contract_Month-to-month,Contract_One year,Contract_Two year
0,0,1,29.85,29.85,No,1,0,0,1,0,0
1,0,34,56.95,1889.50,No,1,0,0,0,1,0
2,0,2,53.85,108.15,Yes,1,0,0,1,0,0
3,0,45,42.30,1840.75,No,1,0,0,0,1,0
4,0,2,70.70,151.65,Yes,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...
7038,0,24,84.80,1990.50,No,1,0,0,0,1,0
7039,0,72,103.20,7362.90,No,0,1,0,0,1,0
7040,0,11,29.60,346.45,No,1,0,0,1,0,0
7041,1,4,74.40,306.60,Yes,0,1,0,1,0,0
7042,0,66,105.65,6844.50,No,0,1,0,0,0,1

In [55]:
# Encode categorical columns using dummy variables
telco_churn = pd.get_dummies(telco_churn, columns=['InternetService', 'Contract'])

In [57]:
telco_churn

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,Churn,InternetService_DSL,InternetService_Fiber optic,InternetService_No,Contract_Month-to-month,Contract_One year,Contract_Two year
0,0,1,29.85,29.85,No,1,0,0,1,0,0
1,0,34,56.95,1889.50,No,1,0,0,0,1,0
2,0,2,53.85,108.15,Yes,1,0,0,1,0,0
3,0,45,42.30,1840.75,No,1,0,0,0,1,0
4,0,2,70.70,151.65,Yes,0,1,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...
7038,0,24,84.80,1990.50,No,1,0,0,0,1,0
7039,0,72,103.20,7362.90,No,0,1,0,0,1,0
7040,0,11,29.60,346.45,No,1,0,0,1,0,0
7041,1,4,74.40,306.60,Yes,0,1,0,1,0,0
7042,0,66,105.65,6844.50,No,0,1,0,0,0,1

In [58]:
telco_churn = df

In [59]:
telco_churn

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No

In [60]:
def prep_telco(telco_churn):
    # Drop unnecessary columns
    telco_churn = telco_churn.drop(['customerID', 'gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 
                        'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
                        'StreamingMovies', 'PaperlessBilling', 'PaymentMethod'], axis=1)

    # Encode categorical columns using dummy variables
    telco = pd.get_dummies(telco, columns=['InternetService', 'Contract'])

    return telco_churn

In [61]:
telco_churn

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,6840-RESVB,Male,0,Yes,Yes,24,Yes,Yes,DSL,Yes,...,Yes,Yes,Yes,Yes,One year,Yes,Mailed check,84.80,1990.50,No
7039,2234-XADUH,Female,0,Yes,Yes,72,Yes,Yes,Fiber optic,No,...,Yes,No,Yes,Yes,One year,Yes,Credit card (automatic),103.20,7362.90,No
7040,4801-JZAZL,Female,0,Yes,Yes,11,No,No phone service,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.60,346.45,No
7041,8361-LTMKD,Male,1,Yes,No,4,Yes,Yes,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,74.40,306.60,Yes
7042,3186-AJIEK,Male,0,No,No,66,Yes,No,Fiber optic,Yes,...,Yes,Yes,Yes,Yes,Two year,Yes,Bank transfer (automatic),105.65,6844.50,No

In [63]:
df = acquire.get_data()

Enter a name for the CSV file: iris.csv
Enter the name of the database you want to access: iris_db
Enter the name of the table you want to access: measurements
File doesn't exist.
Establishing connection and diplaying query
Diplaying query
Enter a name for the CSV file to cache the data: iris.csv
Saved data to iris.csv

In [64]:
import pandas as pd
from sklearn.model_selection import train_test_split

def split_data(df):
    # Split the data into training, testing, and validation sets
    train, test = train_test_split(df, test_size=0.2, random_state=123)
    train, validate = train_test_split(train, test_size=0.25, random_state=123)

    return train, validate, test

# Load the Iris dataset
iris = pd.read_csv('iris.csv')

# Split the Iris dataset into training, testing, and validation sets
train, validate, test = split_data(iris)

# Load the Titanic dataset
titanic = pd.read_csv('titanic.csv')

# Split the Titanic dataset into training, testing, and validation sets
train, validate, test = split_data(titanic)

# Load the Telco dataset
telco_churn = pd.read_csv('telco_churn.csv')

# Split the Telco dataset into training, testing, and validation sets
train, validate, test = split_data(telco_churn)

In [65]:
split_data(iris)

(     measurement_id  sepal_length  sepal_width  petal_length  petal_width  \
 86               87           6.7          3.1           4.7          1.5
 82               83           5.8          2.7           3.9          1.2
 109             110           7.2          3.6           6.1          2.5
 147             148           6.5          3.0           5.2          2.0
 49               50           5.0          3.3           1.4          0.2
 94               95           5.6          2.7           4.2          1.3
 56               57           6.3          3.3           4.7          1.6
 40               41           5.0          3.5           1.3          0.3
 70               71           5.9          3.2           4.8          1.8
 23               24           5.1          3.3           1.7          0.5
 139             140           6.9          3.1           5.4          2.1
 149             150           5.9          3.0           5.1          1.8
 68               69           6.2          2.2           4.5          1.5
 64               65           5.6          2.9           3.6          1.3
 98               99           5.1          2.5           3.0          1.1
 81               82           5.5          2.4           3.7          1.0
 129             130           7.2          3.0           5.8          1.6
 57               58           4.9          2.4           3.3          1.0
 83               84           6.0          2.7           5.1          1.6
 75               76           6.6          3.0           4.4          1.4
 143             144           6.8          3.2           5.9          2.3
 84               85           5.4          3.0           4.5          1.5
 110             111           6.5          3.2           5.1          2.0
 43               44           5.0          3.5           1.6          0.6
 17               18           5.1          3.5           1.4          0.3
 122             123           7.7          2.8           6.7          2.0
 12               13           4.8          3.0           1.4          0.1
 119             120           6.0          2.2           5.0          1.5
 48               49           5.3          3.7           1.5          0.2
 100             101           6.3          3.3           6.0          2.5
 35               36           5.0          3.2           1.2          0.2
 120             121           6.9          3.2           5.7          2.3
 61               62           5.9          3.0           4.2          1.5
 142             143           5.8          2.7           5.1          1.9
 131             132           7.9          3.8           6.4          2.0
 79               80           5.7          2.6           3.5          1.0
 140             141           6.7          3.1           5.6          2.4
 41               42           4.5          2.3           1.3          0.3
 102             103           7.1          3.0           5.9          2.1
 114             115           5.8          2.8           5.1          2.4
 19               20           5.1          3.8           1.5          0.3
 9                10           4.9          3.1           1.5          0.1
 60               61           5.0          2.0           3.5          1.0
 26               27           5.0          3.4           1.6          0.4
 97               98           6.2          2.9           4.3          1.3
 76               77           6.8          2.8           4.8          1.4
 18               19           5.7          3.8           1.7          0.3
 107             108           7.3          2.9           6.3          1.8
 0                 1           5.1          3.5           1.4          0.2
 51               52           6.4          3.2           4.5          1.5
 134             135           6.1          2.6           5.6          1.4
 11               12           4.8          3.4           1.6          0.2
 101             102           5.8          2.7           5.1          1.9
 71               72           6.1          2.8           4.0          1.3
 5                 6           5.4          3.9           1.7          0.4
 128             129           6.4          2.8           5.6          2.1
 30               31           4.8          3.1           1.6          0.2
 47               48           4.6          3.2           1.4          0.2
 137             138           6.4          3.1           5.5          1.8
 126             127           6.2          2.8           4.8          1.8
 44               45           5.1          3.8           1.9          0.4
 92               93           5.8          2.6           4.0          1.2
 29               30           4.7          3.2           1.6          0.2
 10               11           5.4          3.7           1.5          0.2
 14               15           5.8          4.0           1.2          0.2
 146             147           6.3          2.5           5.0          1.9
 58               59           6.6          2.9           4.6          1.3
 85               86           6.0          3.4           4.5          1.6
 144             145           6.7          3.3           5.7          2.5
 74               75           6.4          2.9           4.3          1.3
 27               28           5.2          3.5           1.5          0.2
 106             107           4.9          2.5           4.5          1.7
 89               90           5.5          2.5           4.0          1.3
 148             149           6.2          3.4           5.4          2.3
 50               51           7.0          3.2           4.7          1.4
 95               96           5.7          3.0           4.2          1.2
 3                 4           4.6          3.1           1.5          0.2
 25               26           5.0          3.0           1.6          0.2
 2                 3           4.7          3.2           1.3          0.2
 67               68           5.8          2.7           4.1          1.0
 105             106           7.6          3.0           6.6          2.1
 80               81           5.5          2.4           3.8          1.1
 73               74           6.1          2.8           4.7          1.2
 52               53           6.9          3.1           4.9          1.5
 53               54           5.5          2.3           4.0          1.3
 78               79           6.0          2.9           4.5          1.5
 55               56           5.7          2.8           4.5          1.3
 125             126           7.2          3.2           6.0          1.8
 22               23           4.6          3.6           1.0          0.2
 113             114           5.7          2.5           5.0          2.0

      species_id
 86            2
 82            2
 109           3
 147           3
 49            1
 94            2
 56            2
 40            1
 70            2
 23            1
 139           3
 149           3
 68            2
 64            2
 98            2
 81            2
 129           3
 57            2
 83            2
 75            2
 143           3
 84            2
 110           3
 43            1
 17            1
 122           3
 12            1
 119           3
 48            1
 100           3
 35            1
 120           3
 61            2
 142           3
 131           3
 79            2
 140           3
 41            1
 102           3
 114           3
 19            1
 9             1
 60            2
 26            1
 97            2
 76            2
 18            1
 107           3
 0             1
 51            2
 134           3
 11            1
 101           3
 71            2
 5             1
 128           3
 30            1
 47            1
 137           3
 126           3
 44            1
 92            2
 29            1
 10            1
 14            1
 146           3
 58            2
 85            2
 144           3
 74            2
 27            1
 106           3
 89            2
 148           3
 50            2
 95            2
 3             1
 25            1
 2             1
 67            2
 105           3
 80            2
 73            2
 52            2
 53            2
 78            2
 55            2
 125           3
 22            1
 113           3  ,
      measurement_id  sepal_length  sepal_width  petal_length  petal_width  \
 62               63           6.0          2.2           4.0          1.0
 66               67           5.6          3.0           4.5          1.5
 123             124           6.3          2.7           4.9          1.8
 111             112           6.4          2.7           5.3          1.9
 124             125           6.7          3.3           5.7          2.1
 91               92           6.1          3.0           4.6          1.4
 96               97           5.7          2.9           4.2          1.3
 108             109           6.7          2.5           5.8          1.8
 136             137           6.3          3.4           5.6          2.4
 103             104           6.3          2.9           5.6          1.8
 21               22           5.1          3.7           1.5          0.4
 16               17           5.4          3.9           1.3          0.4
 93               94           5.0          2.3           3.3          1.0
 130             131           7.4          2.8           6.1          1.9
 145             146           6.7          3.0           5.2          2.3
 34               35           4.9          3.1           1.5          0.2
 7                 8           5.0          3.4           1.5          0.2
 1                 2           4.9          3.0           1.4          0.2
 39               40           5.1          3.4           1.5          0.2
 69               70           5.6          2.5           3.9          1.1
 115             116           6.4          3.2           5.3          2.3
 99              100           5.7          2.8           4.1          1.3
 77               78           6.7          3.0           5.0          1.7
 6                 7           4.6          3.4           1.4          0.3
 54               55           6.5          2.8           4.6          1.5
 65               66           6.7          3.1           4.4          1.4
 118             119           7.7          2.6           6.9          2.3
 38               39           4.4          3.0           1.3          0.2
 32               33           5.2          4.1           1.5          0.1
 15               16           5.7          4.4           1.5          0.4

      species_id
 62            2
 66            2
 123           3
 111           3
 124           3
 91            2
 96            2
 108           3
 136           3
 103           3
 21            1
 16            1
 93            2
 130           3
 145           3
 34            1
 7             1
 1             1
 39            1
 69            2
 115           3
 99            2
 77            2
 6             1
 54            2
 65            2
 118           3
 38            1
 32            1
 15            1  ,
      measurement_id  sepal_length  sepal_width  petal_length  petal_width  \
 72               73           6.3          2.5           4.9          1.5
 112             113           6.8          3.0           5.5          2.1
 132             133           6.4          2.8           5.6          2.2
 88               89           5.6          3.0           4.1          1.3
 37               38           4.9          3.6           1.4          0.1
 138             139           6.0          3.0           4.8          1.8
 87               88           6.3          2.3           4.4          1.3
 42               43           4.4          3.2           1.3          0.2
 8                 9           4.4          2.9           1.4          0.2
 90               91           5.5          2.6           4.4          1.2
 141             142           6.9          3.1           5.1          2.3
 33               34           5.5          4.2           1.4          0.2
 59               60           5.2          2.7           3.9          1.4
 116             117           6.5          3.0           5.5          1.8
 135             136           7.7          3.0           6.1          2.3
 104             105           6.5          3.0           5.8          2.2
 36               37           5.5          3.5           1.3          0.2
 13               14           4.3          3.0           1.1          0.1
 63               64           6.1          2.9           4.7          1.4
 45               46           4.8          3.0           1.4          0.3
 28               29           5.2          3.4           1.4          0.2
 133             134           6.3          2.8           5.1          1.5
 24               25           4.8          3.4           1.9          0.2
 127             128           6.1          3.0           4.9          1.8
 46               47           5.1          3.8           1.6          0.2
 20               21           5.4          3.4           1.7          0.2
 31               32           5.4          3.4           1.5          0.4
 121             122           5.6          2.8           4.9          2.0
 117             118           7.7          3.8           6.7          2.2
 4                 5           5.0          3.6           1.4          0.2

      species_id
 72            2
 112           3
 132           3
 88            2
 37            1
 138           3
 87            2
 42            1
 8             1
 90            2
 141           3
 33            1
 59            2
 116           3
 135           3
 104           3
 36            1
 13            1
 63            2
 45            1
 28            1
 133           3
 24            1
 127           3
 46            1
 20            1
 31            1
 121           3
 117           3
 4             1  )

In [66]:
split_data(titanic)

(     passenger_id  survived  pclass     sex   age  sibsp  parch     fare  \
 444           444         1       3    male   NaN      0      0   8.1125
 30             30         0       1    male  40.0      0      0  27.7208
 137           137         0       1    male  37.0      1      0  53.1000
 692           692         1       3    male   NaN      0      0  56.4958
 190           190         1       2  female  32.0      0      0  13.0000
 ..            ...       ...     ...     ...   ...    ...    ...      ...
 653           653         1       3  female   NaN      0      0   7.8292
 20             20         0       2    male  35.0      0      0  26.0000
 589           589         0       3    male   NaN      0      0   8.0500
 514           514         0       3    male  24.0      0      0   7.4958
 281           281         0       3    male  28.0      0      0   7.8542

     embarked   class deck  embark_town  alone
 444        S   Third  NaN  Southampton      1
 30         C   First  NaN    Cherbourg      1
 137        S   First    C  Southampton      0
 692        S   Third  NaN  Southampton      1
 190        S  Second  NaN  Southampton      1
 ..       ...     ...  ...          ...    ...
 653        Q   Third  NaN   Queenstown      1
 20         S  Second  NaN  Southampton      1
 589        S   Third  NaN  Southampton      1
 514        S   Third  NaN  Southampton      1
 281        S   Third  NaN  Southampton      1

 [534 rows x 13 columns],
      passenger_id  survived  pclass     sex   age  sibsp  parch      fare  \
 639           639         0       3    male   NaN      1      0   16.1000
 611           611         0       3    male   NaN      0      0    7.0500
 53             53         1       2  female  29.0      1      0   26.0000
 334           334         1       1  female   NaN      1      0  133.6500
 499           499         0       3    male  24.0      0      0    7.7958
 ..            ...       ...     ...     ...   ...    ...    ...       ...
 46             46         0       3    male   NaN      1      0   15.5000
 126           126         0       3    male   NaN      0      0    7.7500
 324           324         0       3    male   NaN      8      2   69.5500
 232           232         0       2    male  59.0      0      0   13.5000
 656           656         0       3    male   NaN      0      0    7.8958

     embarked   class deck  embark_town  alone
 639        S   Third  NaN  Southampton      0
 611        S   Third  NaN  Southampton      1
 53         S  Second  NaN  Southampton      0
 334        S   First  NaN  Southampton      0
 499        S   Third  NaN  Southampton      1
 ..       ...     ...  ...          ...    ...
 46         Q   Third  NaN   Queenstown      0
 126        Q   Third  NaN   Queenstown      1
 324        S   Third  NaN  Southampton      0
 232        S  Second  NaN  Southampton      1
 656        S   Third  NaN  Southampton      1

 [178 rows x 13 columns],
      passenger_id  survived  pclass     sex   age  sibsp  parch     fare  \
 172           172         1       3  female   1.0      1      1  11.1333
 524           524         0       3    male   NaN      0      0   7.2292
 452           452         0       1    male  30.0      0      0  27.7500
 170           170         0       1    male  61.0      0      0  33.5000
 620           620         0       3    male  27.0      1      0  14.4542
 ..            ...       ...     ...     ...   ...    ...    ...      ...
 388           388         0       3    male   NaN      0      0   7.7292
 338           338         1       3    male  45.0      0      0   8.0500
 827           827         1       2    male   1.0      0      2  37.0042
 773           773         0       3    male   NaN      0      0   7.2250
 221           221         0       2    male  27.0      0      0  13.0000

     embarked   class deck  embark_town  alone
 172        S   Third  NaN  Southampton      0
 524        C   Third  NaN    Cherbourg      1
 452        C   First    C    Cherbourg      1
 170        S   First    B  Southampton      1
 620        C   Third  NaN    Cherbourg      0
 ..       ...     ...  ...          ...    ...
 388        Q   Third  NaN   Queenstown      1
 338        S   Third  NaN  Southampton      1
 827        C  Second  NaN    Cherbourg      0
 773        C   Third  NaN    Cherbourg      1
 221        S  Second  NaN  Southampton      1

 [179 rows x 13 columns])

In [67]:
split_data(telco_churn)

(      customerID  gender  SeniorCitizen Partner Dependents  tenure  \
 440   0771-WLCLA  Female              0     Yes        Yes      16
 67    3410-YOQBQ  Female              0      No         No      31
 600   5839-SUYVZ    Male              0      No         No      16
 4883  5233-GEEAX    Male              1      No         No       8
 1258  5529-GIBVH  Female              0      No         No      47
 ...          ...     ...            ...     ...        ...     ...
 1794  5377-NDTOU  Female              0     Yes        Yes      71
 817   0036-IHMOT  Female              0     Yes        Yes      55
 901   9734-YWGEX  Female              0      No         No       9
 1987  5419-KLXBN  Female              0     Yes        Yes      25
 6958  3078-ZKNTS  Female              0     Yes        Yes      13

      PhoneService     MultipleLines InternetService       OnlineSecurity  ...  \
 440           Yes               Yes     Fiber optic                  Yes  ...
 67            Yes                No             DSL                   No  ...
 600           Yes                No     Fiber optic                   No  ...
 4883           No  No phone service             DSL                   No  ...
 1258          Yes                No              No  No internet service  ...
 ...           ...               ...             ...                  ...  ...
 1794          Yes               Yes             DSL                  Yes  ...
 817           Yes                No     Fiber optic                   No  ...
 901           Yes               Yes     Fiber optic                   No  ...
 1987          Yes                No     Fiber optic                   No  ...
 6958          Yes                No              No  No internet service  ...

          DeviceProtection          TechSupport          StreamingTV  \
 440                   Yes                  Yes                  Yes
 67                    Yes                  Yes                  Yes
 600                    No                  Yes                   No
 4883                  Yes                   No                   No
 1258  No internet service  No internet service  No internet service
 ...                   ...                  ...                  ...
 1794                  Yes                  Yes                  Yes
 817                   Yes                  Yes                  Yes
 901                   Yes                   No                  Yes
 1987                  Yes                   No                  Yes
 6958  No internet service  No internet service  No internet service

           StreamingMovies        Contract PaperlessBilling  \
 440                   Yes  Month-to-month              Yes
 67                    Yes        Two year               No
 600                    No  Month-to-month              Yes
 4883                   No  Month-to-month              Yes
 1258  No internet service        Two year               No
 ...                   ...             ...              ...
 1794                  Yes        Two year               No
 817                   Yes        One year              Yes
 901                   Yes  Month-to-month               No
 1987                   No  Month-to-month              Yes
 6958  No internet service        Two year              Yes

                   PaymentMethod MonthlyCharges  TotalCharges  Churn
 440            Electronic check         112.95       1882.55     No
 67                 Mailed check          79.20       2497.20     No
 600     Credit card (automatic)          74.55       1170.50     No
 4883           Electronic check          29.40        221.90    Yes
 1258               Mailed check          20.15       1046.20     No
 ...                         ...            ...           ...    ...
 1794               Mailed check          91.05       6293.75     No
 817   Bank transfer (automatic)         103.70       5656.75     No
 901     Credit card (automatic)          98.30        923.50    Yes
 1987  Bank transfer (automatic)          89.15       2257.75    Yes
 6958  Bank transfer (automatic)          19.75        246.70     No

 [4225 rows x 21 columns],
       customerID  gender  SeniorCitizen Partner Dependents  tenure  \
 5854  7876-BEUTG  Female              0      No         No      15
 797   6286-ZHAOK  Female              0     Yes        Yes      20
 3188  0587-DMGBH  Female              0      No         No       8
 2254  7322-OCWHC    Male              1     Yes         No      72
 5732  1580-BMCMR    Male              1      No         No      19
 ...          ...     ...            ...     ...        ...     ...
 1045  3524-WQDSG  Female              0     Yes        Yes      43
 4365  4737-HOBAX    Male              0     Yes         No      63
 5649  6147-CBCRA  Female              0     Yes         No      33
 5198  0643-OKLRP  Female              1     Yes         No      47
 2141  6648-INWPS    Male              0     Yes        Yes      16

      PhoneService MultipleLines InternetService       OnlineSecurity  ...  \
 5854          Yes           Yes             DSL                   No  ...
 797           Yes           Yes              No  No internet service  ...
 3188          Yes            No             DSL                  Yes  ...
 2254          Yes           Yes     Fiber optic                  Yes  ...
 5732          Yes            No     Fiber optic                  Yes  ...
 ...           ...           ...             ...                  ...  ...
 1045          Yes           Yes     Fiber optic                   No  ...
 4365          Yes           Yes             DSL                   No  ...
 5649          Yes            No              No  No internet service  ...
 5198          Yes           Yes     Fiber optic                  Yes  ...
 2141          Yes            No              No  No internet service  ...

          DeviceProtection          TechSupport          StreamingTV  \
 5854                   No                   No                   No
 797   No internet service  No internet service  No internet service
 3188                   No                   No                   No
 2254                  Yes                  Yes                   No
 5732                   No                   No                   No
 ...                   ...                  ...                  ...
 1045                  Yes                   No                  Yes
 4365                  Yes                  Yes                  Yes
 5649  No internet service  No internet service  No internet service
 5198                   No                   No                   No
 2141  No internet service  No internet service  No internet service

           StreamingMovies        Contract PaperlessBilling  \
 5854                   No  Month-to-month              Yes
 797   No internet service  Month-to-month              Yes
 3188                   No  Month-to-month              Yes
 2254                   No        Two year              Yes
 5732                  Yes  Month-to-month              Yes
 ...                   ...             ...              ...
 1045                  Yes  Month-to-month              Yes
 4365                  Yes        Two year               No
 5649  No internet service  Month-to-month               No
 5198                   No  Month-to-month               No
 2141  No internet service  Month-to-month               No

                   PaymentMethod MonthlyCharges  TotalCharges  Churn
 5854               Mailed check          48.80        720.10     No
 797   Bank transfer (automatic)          25.55        507.40     No
 3188           Electronic check          49.85        365.55    Yes
 2254  Bank transfer (automatic)          93.05       6735.05     No
 5732           Electronic check          87.30       1637.30     No
 ...                         ...            ...           ...    ...
 1045  Bank transfer (automatic)          99.30       4209.95     No
 4365    Credit card (automatic)          79.80       5034.05     No
 5649               Mailed check          20.05        669.45     No
 5198           Electronic check          80.35       3825.85    Yes
 2141           Electronic check          20.15        341.35     No

 [1409 rows x 21 columns],
       customerID  gender  SeniorCitizen Partner Dependents  tenure  \
 941   0811-GSDTP  Female              0      No        Yes      13
 1404  1970-KKFWL  Female              0      No         No      35
 5515  2892-GESUL  Female              0     Yes        Yes      18
 3684  2842-BCQGE    Male              0      No         No      43
 7017  4807-IZYOZ  Female              0      No         No      51
 ...          ...     ...            ...     ...        ...     ...
 2464  2609-IAICY  Female              0      No         No       1
 5585  4667-OHGKG    Male              0      No         No       1
 804   3138-BKYAV    Male              0      No         No       6
 3190  3745-HRPHI    Male              0     Yes        Yes      66
 3266  0464-WJTKO  Female              0     Yes        Yes      72

      PhoneService     MultipleLines InternetService       OnlineSecurity  ...  \
 941            No  No phone service             DSL                   No  ...
 1404          Yes               Yes              No  No internet service  ...
 5515          Yes                No              No  No internet service  ...
 3684          Yes               Yes     Fiber optic                   No  ...
 7017          Yes                No              No  No internet service  ...
 ...           ...               ...             ...                  ...  ...
 2464          Yes               Yes     Fiber optic                   No  ...
 5585          Yes                No              No  No internet service  ...
 804           Yes                No     Fiber optic                   No  ...
 3190           No  No phone service             DSL                   No  ...
 3266          Yes                No              No  No internet service  ...

          DeviceProtection          TechSupport          StreamingTV  \
 941                    No                   No                   No
 1404  No internet service  No internet service  No internet service
 5515  No internet service  No internet service  No internet service
 3684                   No                   No                   No
 7017  No internet service  No internet service  No internet service
 ...                   ...                  ...                  ...
 2464                   No                   No                   No
 5585  No internet service  No internet service  No internet service
 804                    No                   No                  Yes
 3190                  Yes                  Yes                  Yes
 3266  No internet service  No internet service  No internet service

           StreamingMovies        Contract PaperlessBilling  \
 941                    No  Month-to-month               No
 1404  No internet service        Two year               No
 5515  No internet service        Two year               No
 3684                   No  Month-to-month              Yes
 7017  No internet service        Two year               No
 ...                   ...             ...              ...
 2464                   No  Month-to-month              Yes
 5585  No internet service  Month-to-month              Yes
 804                    No  Month-to-month              Yes
 3190                  Yes        Two year               No
 3266  No internet service        Two year               No

                   PaymentMethod MonthlyCharges  TotalCharges  Churn
 941            Electronic check          30.15        382.20     No
 1404  Bank transfer (automatic)          23.30        797.10     No
 5515               Mailed check          19.35        309.25     No
 3684    Credit card (automatic)          75.35       3161.40     No
 7017  Bank transfer (automatic)          20.65       1020.75     No
 ...                         ...            ...           ...    ...
 2464           Electronic check          77.15         77.15    Yes
 5585               Mailed check          19.30         19.30    Yes
 804            Electronic check          85.35        489.45    Yes
 3190  Bank transfer (automatic)          54.65       3632.00     No
 3266  Bank transfer (automatic)          20.10       1460.85     No

 [1409 rows x 21 columns])